### ISSUE TITLE
New release including upgrade to pypsa 0.11

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#100]
@ClaraBuettner was able to run eTraGo with pypsa 0.11. within this [branch](https://github.com/openego/eTraGo/tree/feature/upgrade-to-pypsa-11).
After intensively thinking and talking about the best procedure to change eTraGo to use the new PyPSA version, I suggest the following:

- [x] merging the branch into dev via the PR #94 @ulfmueller 
- [x] cherry-picking the pypsa 0.11 specific commits into all feature branches in eTraGo @ClaraBuettner   EDIT: besides the snapshot clustering branches. they still work with pypsa 0.8
- [x] merging the updated pypsa-fork branch int the pypsa-fork dev branch via this [PR](https://github.com/openego/PyPSA/pull/3) @ulfmueller
~~- [ ] pull changes from PyPSA fork dev into the [snapshot clustering branch](https://github.com/openego/PyPSA/tree/features/snapshot_clustering) @ulfmueller~~
EDIT: no because right now it seemed more convenient to leave it to the old pypsa version therefore the snaphshot clustering is still working on 0.8 but this will be changed as soon as the function is merged into dev.
- [x] merge the PyPSA fork dev into master @ulfmueller
- [x] merge the eTraGo dev into master @ulfmueller
- [x] change the setup.py in eTraGo master linking to the pypsa fork master @ulfmueller
- [x] release the eTraGo master with tag v0.5. @ulfmueller

If there are no objections I would proceed tomorrow morning. @BartelsJ @wolfbunke @lukasoldi

**Comment by lukasoldi** [comment]
I like the idea and am curious on how the new version will perform ;-)

**Comment by ulfmueller** [comment]
fyi: I won't start with the upgrading procedure today and postpone it to the beginning of next week.

**Comment by wolfbunke** [comment]
I was testing the pypsa 0.11 branch with eGo and also used it in Branch [ feature/line-expansion-p11](https://github.com/openego/eTraGo/tree/feature/line-expansion-p11) which works fine. Please make sure that etrago is not executable by it self with ` network = etrago(args)` at the end of the script. Thanks a lot!

**Comment by ulfmueller** [comment]
> Please make sure that etrago is not executable by it self with network = etrago(args) at the end of the script. 
Because of the read-the-docs?

**Comment by wolfbunke** [comment]
Yes for read-the-docs but manly for the etrago import into eGo with `from etrago.appl import etrago`

**Comment by ulfmueller** [comment]
@ClaraBuettner Could you please proceed with the cherry picking?! and check the box once your done.... Thank you in advance!!

**Comment by ClaraBuettner** [comment]
I started cherry-picking, but in some branches, it causes problems because they don't have the same structure like the dev-branch. So I was not able to update: lines_optimisation, load-shedding-analysis, marginal_cost_noise. All of them do not have the folder etrago/tools including the io.py.
Up to now I havn't updated the sorage-paper-branch, beause I'm not sure if I should do this.

**Comment by wolfbunke** [comment]
The mayor features of branch` lines_optimisation` are implemented in` line-expansion-p11`.  An update by  cherry picking is not needed for this branch.  The branches ` load-shedding-analysis` and `marginal_cost_noise` looks like early works of etrago and I am not sure if those branches are still relevant? @ulfmueller

**Comment by ulfmueller** [comment]
These branches are still somewhat relevant. @ClaraBuettner could you try to update these branches by pulling all changes from dev?

**Comment by ClaraBuettner** [comment]
I just tried to do this, but there are merge confilcts in the appl.py and I don't know wihich changes the branches need. And the old branches have files which were deleted, and I'm not sure what to do with them. Maybe we can do this together on thursday?

**Comment by ulfmueller** [comment]
yes. I expected s.th. like this :wink: 
Or may be we just leave the old branches and change the setup so that there is a dependency link to the commit on pypsa dev before the switch to 0.11....

**Comment by ulfmueller** [comment]
fyi: tomorrow morning there will be the release...

**Comment by ulfmueller** [comment]
The release is (almost) done :tada:. What is missing is the release via PyPI. @lukasoldi How did you do that the last two times? with the help of @gplssm ? 
If so, I think it would be more sustainable if someone of the eTraGo team is able to do that as well... I think I already have an account and I would work on getting that competence on monday :wink:

**Comment by lukasoldi** [comment]
Nice! I did it with the help of Berlin, yes...and since this is an issue after each release I also think that we should have an eTraGo-pypi-guy

**Comment by ulfmueller** [comment]
I dealt with that PyPI release. Since there is some restructuring going on in the PyPI world it was a bit more tricky than expected (see also: https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html). In the end I committed the mistake to delete the project in order to re-upload the version to PyPI which apparently is not possible (see e.g. https://github.com/pypa/packaging-problems/issues/74 ). 
BTW: We have not had a release pushed to PyPI so far (and nobody really missed this). This time it would have been the first time. 
I would suggest to just wait until the next release to also publish it on PyPI.
Now I am all set to do that.

**Comment by ulfmueller** [comment]
If nobody disagrees I will close this issue without publishing on PyPI.
For the next release I created a milestone, which you can use for existing and upcoming issues.

**Comment by gplssm** [comment]
> I dealt with that PyPI release. Since there is some restructuring going on in the PyPI world it was a bit more tricky than expected (see also: https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html). In the end I committed the mistake to delete the project in order to re-upload the version to PyPI which apparently is not possible (see e.g. https://github.com/pypa/packaging-problems/issues/74 ). 
> BTW: We have not had a release pushed to PyPI so far (and nobody really missed this). This time it would have been the first time. 
> I would suggest to just wait until the next release to also publish it on PyPI.
> Now I am all set to do that.

I published a release of Ding0 on the 1st of September. I remember something changed with PyPi. Anyways, somehow I made. Sadly, I cannot remember it in detail. At least I can tell that I used the following cofiguration in the `.pypirc`
```
[pypi]
repository: https://pypi.python.org/pypi
```

**Comment by ulfmueller** [comment]
apparently now it is not possible anymore to do it with that https. Now you have to enter this address:     repository:https://upload.pypi.org/legacy/
or even better upgrade twine/setuptools and leave out the https in total. 
During this learning process I thought deleting that half-published version would be a good idea which it wasnt since deleted versions cannot be uploaded again...
thats how I got stucked. The new process I think is no problem anymore...
