### ISSUE TITLE
Arrows on line loading plot

### ISSUE THREAD

**Issue by MarlonSchlemminger** [openego/eTraGo#103]
Since September, plot_line_loading has the option to get arrows indicating the direction of the electricity flow for each line. I found three possible ways to do this in matplotlib:
1. Annotate: This is how it is implemented currently in the dev branch (https://github.com/openego/eTraGo/blob/dev/etrago/tools/plot.py#L97-L116). Each line gets an annotation of a small arrow. The downside is that it is very slow, because each arrow is annotated on its own, whereas the lineplot itself is plotted via a linecollection, which is a lot faster. This also makes zooming in and out very slow.
2. Arrows
3. Quiver: Both arrows and especially quiver looked more complicated to me and I couldn't find any difference in performance. I did some small experiments with both options which can still be found here (https://github.com/openego/eTraGo/blob/features/arrows-on-line-loading/etrago/tools/plot.py#L97-L139).
It would be nice if we could find a way to make the arrow plot faster. My idea would be to create a collection for the arrows as well as this is generally the way python plots large amounts of objects in a fast way, but I couldn't implement it for the arrows. If anyone has an idea, feel free to comment so that I can work on it or implement it yourself.
@ulfmueller Feel free to assign anyone you tthink would be viable for this issue.
![arrows](https://user-images.githubusercontent.com/22960010/33202952-a8b22968-d0fe-11e7-828a-cd73e25da66d.png)

**Comment by BartelsJ** [comment]
Thank you for pushing this. 
I am not sure whether I understand this collection approach you tried, but I was thinking about the possibility to use interactive plots with the plotly package therefore as a compromise. So basically using a (fast) line plot, but also have the possibility to generate arrows by clicking on lines or something similar?

**Comment by MarlonSchlemminger** [comment]
The collection approach was just a general idea. To plot large amounts of lines, you wrap them into a LineCollection which is a lot faster at plotting than plotting them line by line. Similar to a LineCollection, I wanted to create something like an AnnotateCollection (although exactly this does not exist) to plot the arrows faster.
Sure, if we use plotly instead of matplotlib in the future we would have to look into this in plotly. I don't know what the status is with using plotly.

**Comment by ulfmueller** [comment]
> I don't know what the status is with using plotly.

Since we upgraded to pypsa 0.11.0 we can use plotly as one likes!

**Comment by wolfbunke** [comment]
@BartelsJ  you wanted to take this ticket right?

**Comment by ClaraBuettner** [comment]
Adding arrows to the network plots is now directly possible with pypsa.network.plot(). That is also used in eTraGo, so I will close this issue.
