### ISSUE TITLE
Integrating /features/lines_optimization

### ISSUE THREAD

**Issue by wolfbunke** [openego/eTraGo#104]
Test and integrate the functions of branch `/features/lines_optimization` to new pypsa 11 version in branch `feature/line-expansion-p11`

- [x] integrate functions and make it executable @wolfbunke
- [ ] test results @wolfbunke
- [x] remove cost parameters to oedb tables @ClaraBuettner  
- [ ] implement calculations from appl.py as functions  @wolfbunke

**Comment by wolfbunke** [comment]
The functions and scripts are integrated in the pypsa 0.11 environment of `feature/line-expansion-p11` based on the MA work the new functions are removed to the folder tools. 
The two files: 
- line_opti_appl.py -> line_optimization(Masterthesis Dokumentation).py
- line_opti_appl_gekuerzt.py -> line_optimization(gekuerzt).py

are added to the branch and are now executable with pypsa 0.11. see:  389d628 

At the moment the results doesn't show any line extension.
Results are:

> Anzahl lines_time : 0
> Anzahl Trafo_time : 0
> Anzahl All_time : 0
> finish
> 1.7452869852383932

This parts are buggy  at the moment : 

- https://github.com/openego/eTraGo/blob/feature/line-expansion-p11/etrago/line_opti_appl.py#L450
- https://github.com/openego/eTraGo/blob/feature/line-expansion-p11/etrago/line_opti_appl.py#L435-L453
- https://github.com/openego/eTraGo/blob/feature/line-expansion-p11/etrago/tools/plot.py#L740-L752

**Comment by ulfmueller** [comment]
@hftorres63 Are you planning to contribute anymore to this development? Which was the final branch you worked on?

I will focus on this in the upcoming weeks.

**Comment by hftorres63** [comment]
@ulfmueller  I was working on the branch lines_expansions. My last update was yesterday. If I need to change something on the labels, I make some modifications on the following days.
