### ISSUE TITLE
Add aggregation of one ports within k means clustering

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#106]
The k means function we are using is not aggregating the one ports like e.g. generators.
PyPSA has two functions for that: aggregategenerators and aggregateoneports.
The [cluster_on_extra_high_voltage](https://github.com/openego/eTraGo/blob/dev/etrago/cluster/networkclustering.py#L48) uses them [here](https://github.com/openego/eTraGo/blob/dev/etrago/cluster/networkclustering.py#L90-L105).

Something very similar to this we need in the k-means clustering as well. Otherwise the number of generators will be the same as before clustering. The aggregation would make the optimization problem a lot smaller and therefore faster and more RAM feasible.

@BartelsJ Do you think, Jorge could implement this?
Otherwise I would give it try or maybe @wolfbunke ...
I would like to implement this asap since I think it will boost possible yearly calculations and it is rather just a 'sophisticated copy and paste'

**Comment by BartelsJ** [comment]
That is a good point and I did not check the number of generators with the kmeans clustering yet. But ain't the aggregation of those one ports is done [here](https://github.com/PyPSA/PyPSA/blob/master/pypsa/networkclustering.py#L225-L239)?

**Comment by ulfmueller** [comment]
Yes exactly - but they have to be called/used which they are not. In our ehv network clustering it happens but not in our k means clustering.

**Comment by ulfmueller** [comment]
@BartelsJ Any news, if and when Jorge could tackle this?

**Comment by BartelsJ** [comment]
Jorge is quite busy at the moment, but I adapt it in [906c295](https://github.com/openego/eTraGo/commit/906c2959a000c4ad7d6f9c3c61369abc75d1862f) in the KMEANS#77 branch.

**Comment by ulfmueller** [comment]
Wow that it was that simple I did not see coming. Thx a lot! Didnt know that it was already an existing attribute!! Have you tried it out yet? I will do so soon :+1:

**Comment by BartelsJ** [comment]
Same for me - a lot of trials for small changes in the end ;-) 
Yes, I tried it for SH and the generators.csv was reduced like the buses.csv. Besides, the sum of p_nom as well as the sum of the product marginal_cost times appropriate weight in the clustered grid equals the values/sums of the original grid.

**Comment by ulfmueller** [comment]
I tried it out. I think now we have gone a bit too far. There is just one generator per bus. In the ehv network clustering we group over buses and carriers in order to consider different marginal costs in the optimization problem. But it is weird. The aggregategenerator function which is called should group like that because we changed it in the context of the ehv network clustering...

**Comment by ulfmueller** [comment]
I spent my time today on this issue and I found a solution. Apparently the Kmean#77 branch is causing some problems due to the restructuring of the weighting which I did not solve. Now I just added the changes from @BartelsJ to the dev (see 63023ca80b73b276291e5e3e230d7594d00d4db0 )- in order to work with the kmeans normally. It behaves very well.
Moreover I pushed a minor bugfix in our PyPSA dev ([see](https://github.com/openego/PyPSA/commit/a46841084034798ae284eb4eaac373644d93c29c) ). Now the kmeans works with all scenarios.

I am glad it works now in the dev branch. @BartelsJ and @JorgeDLR For me this is solved now.

@wolfbunke if you want the more generic bus weighting method to be merged into dev (which in theory would be nice) you have to work on that branch in order that it works as fine as it does now on the dev branch. I tried to merge dev into that branch but I did not succeed and since I am merely into your code I did not want to solve that issue.

**Comment by BartelsJ** [comment]
Great, thank you Ulf. I just tried it and it also works fine for me. I think this issue can be closed.

**Comment by ulfmueller** [comment]
I would leave it open because I just noticed that the generators a aggregated fine but the oneports are still not. I am on it, I will try to fix that today.

**Comment by ulfmueller** [comment]
https://github.com/openego/PyPSA/commit/75b81175576e7b3472a6fc95c8842dd42d16954c#diff-69c8b0283acf5fbfd2b4d4d71dd7caee

https://github.com/openego/PyPSA/commit/64582875e789086bbc5e1a96a722eefeb4ebea43#diff-69c8b0283acf5fbfd2b4d4d71dd7caee

https://github.com/openego/PyPSA/commit/d4fa9e8f174ecb425e1e67a964285f96f5bc6d71#diff-69c8b0283acf5fbfd2b4d4d71dd7caee

https://github.com/openego/PyPSA/commit/f8013fa81eb7e92879e79b6c80093b0df2d7938f#diff-69c8b0283acf5fbfd2b4d4d71dd7caee

produce a good approach for aggregation of oneports and generators.
