### ISSUE TITLE
Make it possible to merge network_variances into dev

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eTraGo#111]
The branch network_variances includes links, so a few steps have to be done before merging:
- [ ] branch is ready to be merged 
- [ ] add link-tables to model_draft and grid-schema (e.g. model_draft.ego_grid_pf_hv_link), this is also needed for the new electrical-neighbours script, so this can be done at once
- [ ] add entso-e input-tables to oedb
- [ ] add the updated electrical-neighbours script (dataprocessing-branch: feature/electrical_neighbours) 
- [ ] run script to create and fill extension-table (add this to preprocessing?) 

@IlkaCu Unfortunately, the dataprocessing has to be changed for this, tables for links have to be created and the elctrical-neighbour script will be updated. And I'm not sure where to include the SQL-file creating and filling the extension tables. Could you help me?

**Comment by IlkaCu** [comment]
To add link tables to the model_draft you can adjust the script [ego_dp_powerflow_hv_setup.sql](https://github.com/openego/data_processing/blob/release/v0.3/dataprocessing/sql_snippets/ego_dp_powerflow_hv_setup.sql). To include them in the grids schema you have to add them in the [ego_dp_structure_setup.sql.](https://github.com/openego/data_processing/blob/release/v0.3/preprocessing/sql_snippets/ego_dp_structure_versioning.sql) Note that this script is included in the preprocessing and not executed in the normal dataprocessing. Which means you have to execute the setup of those link tables in the grids schema once on your own. You additionally need to add the new link tables to the [versioning script](https://github.com/openego/data_processing/blob/release/v0.3/dataprocessing/sql_snippets/ego_dp_versioning.sql). 

Furthermore you can add the script which fills the link table to the powerflow part of the [dataprocessing.](https://github.com/openego/data_processing/blob/release/v0.3/dataprocessing/eGo_data_processing.py) After the script 'ego_dp_powerflow_grid_future_scenarios.sql' might be a good option. 
Please make sure to create your own branch to add your changes and send a pull request afterwards.

**Comment by ulfmueller** [comment]
Just to follow up on this. @ClaraBuettner What is the status here? Will this be successful once the new data processing release is completed? Are the dp related todos integrated in the upcoming dp release?

**Comment by ClaraBuettner** [comment]
As far as I know, this won't be part of the new dp-release. But it could be used as a post-processing, because link-tables are added. So there is just one postprocessing script needed to add this.

**Comment by IlkaCu** [comment]
I already executed the code to create the link table in the database but it does not contain any data yet. 
Is there any other code which need to be added to the dataprocessing or preprocessing to add data?

**Comment by ulfmueller** [comment]
I would say - this task is entirely done, correct @ClaraBuettner ?
