### ISSUE TITLE
Disaggregation of k-means clustering results

### ISSUE THREAD

**Issue by BartelsJ** [openego/eTraGo#113]
The results of simulations on the basis of the k-means cluster approach have to be disaggregated to the original grid. This ticket is created to work on this.

**Comment by ulfmueller** [comment]
@MGlauer I saw you pushed something in a new feature branch! Nice can you say a few words about it? How can I test it?

**Comment by ulfmueller** [comment]
@MGlauer There are two disaggregation branches:

https://github.com/openego/eTraGo/tree/features/disaggregation
and
https://github.com/openego/eTraGo/tree/feature/disagg

How are they different? Is one obsolete?

**Comment by ulfmueller** [comment]
I talked to @MGlauer The disagg branch is the relevant one. I tried out but I got the following error:

[disagg error.txt](https://github.com/openego/eTraGo/files/1615506/disagg.error.txt)

Do you know this one @MGlauer ? Any hints?

**Comment by ulfmueller** [comment]
Tried it out with glpk - but unfortunately did not work either. Same error message. I would be grateful for hints!

**Comment by ulfmueller** [comment]
@MGlauer / @gnn
Is there any reason why [here](https://github.com/openego/eTraGo/blob/feature/disagg/etrago/cluster/disaggregation.py#L98) and [there](https://github.com/openego/eTraGo/blob/feature/disagg/etrago/cluster/disaggregation.py#L107) you use the attribute 'bus0_s'? I changed it to 'bus0' and it 'worked'. At least the disaggregation was performed. 

The performed disaggregation evoked some observations and questions:
- many of the disaggregation problems are infeasible
- some disaggregation problems consist of various networks/grids/graphs (which does not seem reasonable)
- After the performed disaggregation, where are the decomposed solutions saved? How can one access the decomposed overall grid? At least when I check 'network.buses' I only get the clustered number of buses (e.g. 10 instead of the total number of buses of the original problem e.g. 300)

Maybe it would be good if we can have a little 'hand-over-workshop':
- so @gnn and the others involved (like me) know what the code does or is supposed to do 
- and we can follow up on your work

What do you think? Maybe a webco next week? Monday would fit me for example(maybe @gnn is still here in FL then)

**Comment by ulfmueller** [comment]
@gnn Any news here?

**Comment by ulfmueller** [comment]
@gnn I tested the 'uniform' desaggregation. If I try it out for the entire grid (scn_name NEP 2035) I got the follwoing error:

```
Decompose cluster 8 (1/10)
No data for StoragePqSet in column p_set.
Series p_set of component StorageUnit could not be imported
/usr/local/lib/python3.5/dist-packages/pandas/core/generic.py:2773: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value
Decomposed in  85.64589881896973
/home/ulf/eTraGo/etrago/cluster/disaggregation.py:314: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  [self.clustered_network.generators.carrier == carrier])
/home/ulf/eTraGo/etrago/cluster/disaggregation.py:208: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.transfer_results(partial_network, externals)
Decomposition optimized in  10.86441969871521
---
Decompose cluster 1 (2/10)
No data for StoragePqSet in column p_set.
Series p_set of component StorageUnit could not be imported
Decomposed in  88.36077213287354
Decomposition optimized in  9.802700996398926
---
Decompose cluster 2 (3/10)
No data for StoragePqSet in column p_set.
Series p_set of component StorageUnit could not be imported
Decomposed in  84.77432703971863
Decomposition optimized in  9.824443817138672
---
Decompose cluster 7 (4/10)
No data for StoragePqSet in column p_set.
Series p_set of component StorageUnit could not be imported
Decomposed in  85.6243941783905
Traceback (most recent call last):
  File "appl.py", line 351, in <module>
    network = etrago(args)
  File "appl.py", line 330, in etrago
    disaggregation.execute(scenario, solver=args['solver'])
  File "/home/ulf/eTraGo/etrago/cluster/disaggregation.py", line 179, in execute
    self.solve(scenario, solver)
  File "/home/ulf/eTraGo/etrago/cluster/disaggregation.py", line 207, in solve
    solver)
  File "/home/ulf/eTraGo/etrago/cluster/disaggregation.py", line 317, in solve_partial_network
    "Should be only one.".format(cluster, len(cgs), carrier))
AssertionError: Cluster {} has {} generators for carrier {}. Should be only one.
>>> 

```

Any ideas what this error is about?

**Comment by ulfmueller** [comment]
> After the performed disaggregation, where are the decomposed solutions saved? How can one access the decomposed overall grid? At least when I check 'network.buses' I only get the clustered number of buses (e.g. 10 instead of the total number of buses of the original problem e.g. 300)

This question (see above) I was wondering about again (possibly @MGlauer have told me already some time ago but I must have forgot it).  Anyhow would it be possible that the network resp. network.buses and so on get the decomposed solution?

**Comment by gnn** [comment]
About the assertion error: yeah, I put that in as a sanity check. But apparently I messed up generating the correct message so now I don't know what exactly went wrong.
Should be fixed now.
Putting the decomposed solution on the network is partially working. I need some pointers to what's missing though, to make that work completely.

**Comment by BartelsJ** [comment]
Just as information: Yesterday, I tested it and got the following error while matching original and cluster bus IDs: (Arguments below)

2018-06-21 17:18:59.818078
No data for StoragePqSet in column p_set.
Series p_set of component StorageUnit could not be imported
start k-mean clustering
INFO:pypsa.pf:Slack bus for sub-network 0 is 0
INFO:pypsa.opf:Performed preliminary steps
INFO:pypsa.opf:Building pyomo model using `angles` formulation
INFO:pypsa.opf:Solving model using cplex
INFO:pypsa.opf:Optimization successful
Time for LOPF [min]: 0.01
Investment costs for all storages in selected snapshots [EUR]: 0.0

Decompose cluster 0 (1/50)
No data for StoragePqSet in column p_set.
Series p_set of component StorageUnit could not be imported
Decomposed in  48.0975923538208
Result distributed in  0.19464659690856934
Results transferred in  0.004563570022583008

Decompose cluster 1 (2/50)
No data for StoragePqSet in column p_set.
Series p_set of component StorageUnit could not be imported
Decomposed in  49.26697564125061
Result distributed in  0.23944830894470215
Results transferred in  0.0042612552642822266

Decompose cluster 10 (3/50)
No data for StoragePqSet in column p_set.
Series p_set of component StorageUnit could not be imported
Decomposed in  45.89827537536621
Result distributed in  0.23262453079223633
Results transferred in  0.004379749298095703

Decompose cluster 11 (4/50)
No data for StoragePqSet in column p_set.
Series p_set of component StorageUnit could not be imported
Decomposed in  48.76451754570007
Traceback (most recent call last):

  File "<ipython-input-2-a894517d1f07>", line 1, in <module>
    runfile('/home/jbartels/projekte/open-ego/eTraGo/etrago/appl.py', wdir='/home/jbartels/projekte/open-ego/eTraGo')

  File "/home/jbartels/miniconda3/envs/julian/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "/home/jbartels/miniconda3/envs/julian/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/jbartels/projekte/open-ego/eTraGo/etrago/appl.py", line 441, in <module>
    network = etrago(args)

  File "/home/jbartels/projekte/open-ego/eTraGo/etrago/appl.py", line 410, in etrago
    disaggregation.execute(scenario, solver=args['solver'])

  File "/home/jbartels/projekte/open-ego/eTraGo/etrago/cluster/disaggregation.py", line 192, in execute
    self.solve(scenario, solver)

  File "/home/jbartels/projekte/open-ego/eTraGo/etrago/cluster/disaggregation.py", line 222, in solve
    solver)

  File "/home/jbartels/projekte/open-ego/eTraGo/etrago/cluster/disaggregation.py", line 415, in solve_partial_network
    "it has on the buses of it's partial network.")

AssertionError: The `'p_nom_extendable'` flag for the current cluster's bus does not have the same value it has on the buses of it's partial network.


args = {# Setup and Configuration:
        'db': 'oedb', # db session
        'gridversion': 'v0.3.2', # None for model_draft or Version number (e.g. v0.2.11) for grid schema
        'method': 'lopf', # lopf or pf
        'pf_post_lopf': False, # state whether you want to perform a pf after a lopf simulation
        'start_snapshot': 1,
        'end_snapshot' : 2, #3624,
        'solver': 'cplex', # glpk, cplex or gurobi
        'solver_options': {}, # {} for default settings or dict of solver options
        'scn_name': 'NEP 2035', # # choose a scenario: Status Quo, NEP 2035, eGo100
            # Scenario variations:
            'scn_extension': None, # None or name of additional scenario (in extension_tables) e.g. 'nep2035_b2'
            'scn_decommissioning': None, # None or name of decommissioning-scenario (in extension_tables) e.g. 'nep2035_b2'
            'add_Belgium_Norway': False,  # state if you want to add Belgium and Norway as electrical neighbours, timeseries from scenario NEP 2035!
        # Export options:
        'lpfile': False, # state if and where you want to save pyomo's lp file: False or /path/tofolder
        'results': False,# state if and where you want to save results as csv: False or /path/tofolder
        'export': False, # state if you want to export the results back to the database
        # Settings:
        'extendable':['storages'], # None or array of components you want to optimize (e.g. ['network', 'storages'])
        'generator_noise':True, # state if you want to apply a small generator noise 
        'reproduce_noise': False,# state if you want to use a predefined set of random noise for the given scenario. if so, provide path, e.g. 'noise_values.csv'
        'minimize_loading':False,
        # Clustering:
        'network_clustering_kmeans':50, # state if you want to perform a k-means clustering on the given network. State False or the value k (e.g. 20).
        'load_cluster': False, # state if you want to load cluster coordinates from a previous run: False or /path/tofile (filename similar to ./cluster_coord_k_n_result)
        'network_clustering_ehv': False, # state if you want to perform a clustering of HV buses to EHV buses.
        'disaggregation': 'uniform', # or None, 'mini' or 'uniform'        
        'snapshot_clustering':False, # False or the number of 'periods' you want to cluster to. Move to PyPSA branch:features/snapshot_clustering
        # Simplifications:
        'parallelisation':False, # state if you want to run snapshots parallely.
        'skip_snapshots':False,
        'line_grouping': False, # state if you want to group lines running between the same buses.
        'branch_capacity_factor': 0.7, # globally extend or lower branch capacities
        'load_shedding':False, # meet the demand at very high cost; for debugging purposes.
        'comments':None }

**Comment by ulfmueller** [comment]
The 'uniform' disaggregation works well. I will close this issue for now.
