### ISSUE TITLE
missing confic.json file after pip installation

### ISSUE THREAD

**Issue by wolfbunke** [openego/eTraGo#125]
After I integrated etrago=0.5.1in eGo I got following error:
``` 
FileNotFoundError: [Errno 2] No such file or directory: '../ego_dev/lib/python3.5/site-packages/etrago/tools/config.json'
```

I will add this script part to setup.py  in order to fix the bug.
```
package_data={
        'etrago': [
            os.path.join('tools', '*.json')]
}
```

**Comment by ulfmueller** [comment]
interesting.  Do you think that bug fix is good or rather a work around? 

When does the error occur? In which line is it called? 
Or does it happen already during installation? the pip installation worked fine for me...

**Comment by wolfbunke** [comment]
I think it is good. eDisGo is also using for its different system files see: https://github.com/openego/eDisGo/blob/dev/setup.py#L44-L49 . The error happens during the setup installation because setup.py ignores all csv, json and other files if you use pypi and not` git clone` and  `pip install -e ....` With` package_data` you can point to system relevant files like our config.json in the folder tools for the installation.

**Comment by ulfmueller** [comment]
interesting I did a pure installation with pip install eTraGo and I did not see any error occur. (So I guess the error occurs when io.py calls the function to use the config file...)
But otherwise your solution and explanation sound good to me.
