### ISSUE TITLE
Adjust snapshot clustering to use tsam packages

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#134]
@kimvk will complete the effort of @simnh within this [branch](https://github.com/openego/eTraGo/tree/features/snapshot_clustering_app-tsam)
to use the tsam package instead of the own implementation.
Benefits are:
- we can use other clustering methods like k-means
- we can include peak-periods
- the code is probably a bit more robust and less buggy.

@simnh Will look for a solution of the [timestep issue](https://github.com/FZJ-IEK3-VSA/tsam/issues/5)

**Comment by simnh** [comment]
Ok, I forget that the days do not necessarily have to be 'real' days, depending on the clustering method etc. (see: https://github.com/FZJ-IEK3-VSA/tsam/issues/5) 

Therefore, I propose that we will skip 'real' days and use the standard return value of tsam. The only thing we have to do is the following: 

* create new snapshots (see below for example)
* create new snapshot_weightings (see below for example)
* split data frame by column names and create new p_set dataframes for load and generators based on the dataframe used for clustering. Basically, kind of revert what happend in `prepare_pypsa_timeseries()`(has to be done)


* Add a range(len
 
I used this code for testing the basic functionality of tsam: 

```import tsam.timeseriesaggregation as tsam
import pandas as pd 

raw = pd.read_csv('example/testdata.csv', index_col=0)

aggregation = tsam.TimeSeriesAggregation(raw, noTypicalPeriods = 8, hoursPerPeriod = 24, 
                                        clusterMethod = 'k_means')
df = aggregation.createTypicalPeriods()
weights = aggregation.clusterPeriodNoOccur
aggregation.clusterOrder

timesteps = [i for i in range(0, len(df.index.get_level_values('TimeStep')))]

# reset index to use index levels as normal columns
df = df.reset_index()

# map level 0 to weights
snapshot_weightings = df['level_0'].apply(lambda row: weights[row])

# use the index (0...len(df)) of snapshot weigthings for snapshots
snapshots = snapshot_weightings.index

# set name of Series index and Series (needs to match the standard PyPSA naming)
snapshot_weightings.index.name = 'snapshots'
snapshot_weightings.name = 'weight'

# drop obsolete columns from data frame 
df.drop(['level_0', 'TimeStep'], axis=1, inplace=True)

```

@kimvk do you think you can do this? Probably it's a good way to start and  understand the code above...

**Comment by kimvk** [comment]
I did create new snapshots, snapshot_weightings and create new p_set dataframes for the load and the generators, but there is still a index error coming up:

KeyError: "None of [Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,\n            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,\n            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],\n           dtype='int64', name='snapshots')] are in the [index]"

Do you have a advice? I dont know how to change the timeindex of the whole pypsa model.

**Comment by simnh** [comment]
I am not sure, but maybe the index ends up in an other list somewhere. At which point does the error occur, could you post the full error message?

**Comment by kimvk** [comment]
Traceback (most recent call last):

  File "<ipython-input-2-f1df29ab3aa4>", line 1, in <module>
    runfile('C:/eTraGo/etrago/appl.py', wdir='C:/eTraGo/etrago')

  File "C:\Users\Kim\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\Users\Kim\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/eTraGo/etrago/appl.py", line 334, in <module>
    network = etrago(args)

  File "C:/eTraGo/etrago/appl.py", line 285, in etrago
    network = snapshot_clustering(network, how='daily', clusters= [2])

  File "C:\eTraGo\etrago\cluster\snapshot.py", line 48, in snapshot_clustering
    how=how, normed=False)

  File "C:\eTraGo\etrago\cluster\snapshot.py", line 131, in run
    solver_name='gurobi')

  File "c:\pypsa\pypsa\opf.py", line 1445, in network_lopf
    network_lopf_build_model(network, snapshots, skip_pre=skip_pre, formulation=formulation, ptdf_tolerance=ptdf_tolerance)

  File "c:\pypsa\pypsa\opf.py", line 1273, in network_lopf_build_model
    define_generator_variables_constraints(network,snapshots)

  File "c:\pypsa\pypsa\opf.py", line 83, in define_generator_variables_constraints
    p_min_pu = get_switchable_as_dense(network, 'Generator', 'p_min_pu', snapshots)

  File "c:\pypsa\pypsa\descriptors.py", line 188, in get_switchable_as_dense
    pnl[attr].loc[snapshots, varying_i]

  File "C:\Users\Kim\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1309, in __getitem__
    return self._getitem_tuple(key)

  File "C:\Users\Kim\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 800, in _getitem_tuple
    self._has_valid_tuple(tup)

  File "C:\Users\Kim\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 150, in _has_valid_tuple
    if not self._has_valid_type(k, i):

  File "C:\Users\Kim\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1394, in _has_valid_type
    (key, self.obj._get_axis_name(axis)))

KeyError: "None of [Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,\n            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,\n            34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],\n           dtype='int64', name='snapshots')] are in the [index]"

**Comment by simnh** [comment]
Gibt's hier schon was neues? 

Ich würde mal irgendwo vor dem Fehler angucken mit z.B. `import pdb; pdb.set_trace()` wie das network mit den snapshots / weightings etc. aussieht und  ob das so ist wie du dir das vorstellst, oder hast du das schon gemacht?

**Comment by ulfmueller** [comment]
Any news on this?

**Comment by simnh** [comment]
Some problems occurred. I created a fork where I added some lines of code to actually get the datetimeindex for hierarchical clustering. @kimvk  and I discussed, kim will create a pull request with this functionality for the original tsam repository. 

tsam added already some new functionality but not what we require...but @kim is up-to-date

**Comment by kimvk** [comment]
I did integrate the new code from @simnh from the tsam fork in this [branch](https://github.com/openego/eTraGo/tree/features/snapshot_clustering_app-tsam) and the datetimeindex is now used for further calculations/optimizations. 
But I am wondering why the data of tsam_ts is not matching any data of the original dataframe? For the hierarchical clustering 'real' days are used, so it should fit.

**Comment by simnh** [comment]
What about making a pull request at the original tsam repo, to check what I wrote...maybe there is something wrong with my implementation?

**Comment by kimvk** [comment]
Okay, I will do that

**Comment by kimvk** [comment]
[Get datetimeindex for hierarchical clustering #12](https://github.com/FZJ-IEK3-VSA/tsam/pull/12)

**Comment by ulfmueller** [comment]
successfully implemented in the branches:
dev 
features/snapshot_clustering_analysis (for analysis purposes)
