### ISSUE TITLE
Refactor eTraGo and ego.powerflow

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#14]
the task was to 

1. be able to connect not only to the model_draft schema but also to the versioned grid schema. 
2. write a translater from the database structure which is based on the PyPSA 0.6 model to the PyPSA 0.8 world - without changing the database
3. get rid of io functionalities within the application files and shift that to the io in ego.powerflow
4. find an easy way for working with just one appl.py in order to avoid redundancies and chaos

all this can be found on this [branch](https://github.com/openego/eTraGo/tree/features/adapt-to-ego.powerflow-api/etrago) !

it is still lacking documentation. even though it should be quite intuitive it is not 100% self explanatory. The goal would be to merge this into dev soon (e.g. next week) and have it as the new standard.

The extra_high_voltage_appl.py and  extra_high_voltage_SH_appl.py was already 'merged' into the appl.py. For the 

- [ ] k-means clustering and 
- [ ] snapshot clustering
it is still a pending task

Do you like it? Do you agree? Objections?

**Comment by lukasol** [comment]
I haven't tested anything of the above, but like the idea and initiative very much!

**Comment by ulfmueller** [comment]
now after some bug fixing all the 'old' functionalities seem to work fine in the new structure. I will create a pull request so we can merge this into the dev branch.
