### ISSUE TITLE
Integrate network_variations 

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eTraGo#141]
The possibility to extend and/or decommission components will be integrated. In addition a function to set components extendable will be added. 

- [x] restructure new functions (extension, decommissioning, extendable)

- [x] add documentation of new functions

- [x] change order and names of arguments in appl.py

- [x] change order in appl.py: variations before load_shedding

- [x] integrate storage-costs in annuity-method 

- [x] create issue: position of k_means_clustering

- [x] create and write file 'extendable.py' that contains possible optimization settings (e.g. 'all', 'trafos')

**Comment by ClaraBuettner** [comment]
With network_clustering it is not possible to do load_shedding after the network variations. The clustered network has generators with ids like '23647 biomass'. That trows out an error when I try to apply load_shedding on this:

ValueError: invalid literal for int() with base 10: '23647 biomass'

Is there a way to avoid this @ulfmueller ?

**Comment by ulfmueller** [comment]
True. Mhh, I guess we would have to change the generator aggregation or the load shedding function.
Is this important in this context? Is this a 'new' problem?

**Comment by ClaraBuettner** [comment]
I think its not that complicated to change. I could remove the carrier from the generator_id, since its not needed anymore after clustering. Or I could filter the id column when load_shedding wants to find the maximum. I would prefer the second possibility, then I wouldn't change the result.

**Comment by ulfmueller** [comment]
well, I think removing the carrier from the generator_id is not possible because it is bus_id+carrier. Therefore if you remove the carrier the generator_ids would not be unique anymore. I am not sure if I understand what you want to do for the second option. Isnt the problem that it is a string and not a integer? But in general I am fine with the second solution, if it works :wink:

**Comment by ulfmueller** [comment]
@ClaraBuettner How did you solve this issue in the end? Can we close the issue?

**Comment by ClaraBuettner** [comment]
Yes, this was solved. Just the issue for the position of k_means is missing, I'll create this and close this issue.

**Comment by ClaraBuettner** [comment]
I created the issue to discuss the position of k_means clustering #183
