### ISSUE TITLE
Adjust eTraGo to new carriers wind_onshore/wind_offshore

### ISSUE THREAD

**Issue by MarlonSchlemminger** [openego/eTraGo#142]
With the new DP run, the carrier 'wind' gets split up into 'wind_onshore' and 'wind_offshore' and I try to get an overview of what eTraGo functions need to be adjusted to that. So far I know about:
- plot_stacked_gen
- kmean_clustering

**Comment by ulfmueller** [comment]
@maltesc does the interface functionality towards eDisGo needs some adjustment due to this change?

**Comment by ulfmueller** [comment]
for the k means clustering you mean this [line](https://github.com/openego/eTraGo/blob/dev/etrago/cluster/networkclustering.py#L404), right? 
Well done, that you tackle this!

**Comment by maltesc** [comment]
@ulfmueller, yes, minor changes are necessary. 

I will take care of this during my next simulation run. Should these generators be aggregated in the interface, or will the changes also take place in eDisGo?

**Comment by MarlonSchlemminger** [comment]
> for the k means clustering you mean this line, right?
Yes, exactly.

**Comment by ulfmueller** [comment]
@MarlonSchlemminger @maltesc did you apply your changes? 
@maltesc How was your question answered in the end?
Can we close this issue?

**Comment by MarlonSchlemminger** [comment]
I changed the one line in k_mean_clustering and pushed it and the colors for plotting were already changed by you. Can be closed in my opinion.
