### ISSUE TITLE
release 0.6

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#147]
I suggest to postpone this release to next week (maybe even later) due to several reasons. 
For a clean new release we also need an ego.io release. Since the dp is running at the moment I thought it would be more wise to save the energy to create an ego.io release just being valid for a few days/ couple of weeks. Instead, I would suggest to do this release after the successful dp run 0.4.0, releasing a corresponding ego.io 0.4.0 and then release the eTraGo 0.6.0.
Also then we have a bigger chance to introduce more of the features we are working on in a more solid way.

Instead I will merge more of the features into dev. That will mean that the dev branch will only work with the dev branch of the ego.io.

Any objections?

You can help me by
- checking your issues and dealing with them
- checking the branches you created or you feel responsible for and decide what do with them (clean up a bit the branches)

**Comment by wolfbunke** [comment]
Yes, I guess it is a good way. I already moved issues from milestone 0.6 to 0.7.

**Comment by ulfmueller** [comment]
The 27th of june is release day.
