### ISSUE TITLE
arrows on line loading plot

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#148]
https://github.com/openego/eTraGo/tree/features/arrows-on-line-loading
@MarlonSchlemminger This development was over and already merged into dev or is this still ongoing?
If merged and over, I would like to delete the branch.

**Comment by MarlonSchlemminger** [comment]
See #103. We could still improve this, for example using plotly, but I don't have the time for this. We can delete the branch I think.

**Comment by ClaraBuettner** [comment]
Is this still an open issue?
