### ISSUE TITLE
Structure and responsibilities for eTraGo RTD 

### ISSUE THREAD

**Issue by IlkaCu** [openego/eTraGo#164]
The RTD for eTraGo is about to be revised. The suggested structure of the documentation looks like this. 

* About eTraGo (#165)

* Installation // Getting started (#166)

* How to use eTraGo? (#167)
** Examples/Notebooks

* Theoretical Background and Methods (#168)
** Definitions and Units
** Data Sources
*** Input-/Output data 
*** Scenarios
** Methodology
*** PyPSA
*** Cluster
*** Plots
*** Features
** References

* Notes to developers (#169)

* What’s New (#170)

* API (#171)

**Comment by IlkaCu** [comment]
Feel free to change the assignees of the corresponding issues.

**Comment by wolfbunke** [comment]
The structure is implemented and the single issues almost done.
