### ISSUE TITLE
RTD: 'Theoretical Background and Methods'

### ISSUE THREAD

**Issue by IlkaCu** [openego/eTraGo#168]
The chapter ''Theoretical Background and Methods'' needs to be checked for completeness, tasks need to be derived and improvements should be implemented.

The suggested underlying structure of this part of the documentation looks like the following: 

** Definitions and Units
** Data Sources
*** Input-/Output data
*** Scenarios
** Methodology
*** PyPSA
*** Cluster
*** Plots
*** Features
** References

This structure might be adjusted and additional issues to coordinate related tasks can be created.

**Comment by BartelsJ** [comment]
Further development in [RTD Methods branch](https://github.com/openego/eTraGo/tree/feature/rtd-methods).

**Comment by BartelsJ** [comment]
[Merged](https://github.com/openego/eTraGo/commit/e36ba69012d130d2c04a085cfc63fd23b749bbb2)
