### ISSUE TITLE
Grouping of lines as an option for the appl.py

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#17]
as an idea / nice-to-have we could think about realizing the [simplification in the dp](https://github.com/openego/data_processing/issues/133) within eTraGo and leave the data as it was before...

@lukasol do you have an opinion on that?

**Comment by lukasol** [comment]
Sounds better than doing it on the data side.

**Comment by lukasol** [comment]
Is this resolved and in dev yet?

**Comment by ulfmueller** [comment]
not even close. so far the grouping has been done in sql in the dp. This is a pending task for @mariusves with rather low priority because there is already a sql solution... I would suggest to give it the new milestone...

**Comment by ulfmueller** [comment]
not even close. so far the grouping has been done in sql in the dp. This is a pending task for @mariusves with rather low priority because there is already a sql solution... I would suggest to give it the new milestone...

**Comment by mariusves** [comment]
added first iteration of the python solution in ce04cfc
going to test it by doing several calculations now... Hope everything works so this can be added to the Release 0.3!

**Comment by lukasol** [comment]
Okay, we add to the release. @mariusves please state your testing results here.

**Comment by mariusves** [comment]
Everything looks good so far!
