### ISSUE TITLE
RTD: 'API'

### ISSUE THREAD

**Issue by IlkaCu** [openego/eTraGo#171]
The chapter 'API' needs to be checked for completeness, tasks need to be derived and improvements should be implemented.

**Comment by wolfbunke** [comment]
I check the API and functions here  #175

**Comment by BartelsJ** [comment]
Unfortunately I can't get the check completely done in time for Release 0.7. As far as I see the documentation has a great status, just some functions like i.e. etrago.tools.plot.extension_overlay_network() has to be described.

**Comment by ulfmueller** [comment]
I think we should quickly improve the appearance of the API. The last 4 headers do not display anything and are like this obsolete. Couldn't it be something more simple and clear like in [eDisGo](https://edisgo.readthedocs.io/en/dev/api.html) ? @wolfbunke can you check it out?
