### ISSUE TITLE
No executable for solver gurobi found

### ISSUE THREAD

**Issue by MarlonSchlemminger** [openego/eTraGo#184]
Since today, I get an error that gurobi can not be found on the student account on the server when running the appl.py. Last weekend, the license for gurobi expired and I renewed it via gurobigetkey which worked. Does anyone have an idea why this happened and how to fix it? Clara, Malte, did you do anything on the account yesterday evening or today which might be related to this? I don't just want to try random stuff on the server myself..

INFO:pypsa.opf:Solving model using gurobi
WARNING: Could not locate the 'gurobi' executable, which is required for
    solver gurobi
WARNING:pyomo.solvers:Could not locate the 'gurobi' executable, which is required for solver gurobi
Traceback (most recent call last):
  File "appl.py", line 452, in <module>
    network = etrago(args)
  File "appl.py", line 404, in etrago
    network.lopf(network.snapshots, solver_name=args['solver'], extra_functionality=extra_functionality)
  File "/home/student/marlonsch/lib/python3.5/site-packages/pypsa/opf.py", line 1452, in network_lopf
    return network_lopf_solve(network, snapshots, formulation=formulation, solver_options=solver_options, keep_files=keep_files, free_memory=free_memory)
  File "/home/student/marlonsch/lib/python3.5/site-packages/pypsa/opf.py", line 1377, in network_lopf_solve
    network.results = network.opt.solve(*args, suffixes=["dual"], keepfiles=keep_files, options=solver_options)
  File "/home/student/marlonsch/lib/python3.5/site-packages/pyomo/opt/base/solvers.py", line 541, in solve
    self.available(exception_flag=True)
  File "/home/student/marlonsch/lib/python3.5/site-packages/pyomo/solvers/plugins/solvers/GUROBI.py", line 156, in available
    val = ILMLicensedSystemCallSolver.available(self, exception_flag)
  File "/home/student/marlonsch/lib/python3.5/site-packages/pyomo/opt/solver/ilmcmd.py", line 36, in available
    if not pyomo.opt.solver.shellcmd.SystemCallSolver.available(self, exception_flag):
  File "/home/student/marlonsch/lib/python3.5/site-packages/pyomo/opt/solver/shellcmd.py", line 122, in available
    raise ApplicationError(msg % self.name)
pyutilib.common._exceptions.ApplicationError: No executable found for solver 'gurobi'

**Comment by ClaraBuettner** [comment]
I haven't calculated anything in the last days. Did you tested the new license? Line "val = ILMLicensedSystemCallSolver.available(self, exception_flag)" seems to reference to a license problem. 
To check if gurobi is installed you can type "gurobi.sh" in linux shell.

**Comment by MarlonSchlemminger** [comment]
The license is fine I think, I renewed it on Monday I think and everything worked until this morning and the license file says it expires 2019-06-18. I think it is coincidence that the word license appears in the error log. 

gurobi.sh says Befehl nicht gefunden, both in my environment and outside of it. Does this mean gurobi is not installed anymore? Because the gurobi folder still exists..

**Comment by ClaraBuettner** [comment]
Yes, I'm quite sure that this means that it's not installed anymore, normally it would open a gurobi shell. But when it once worked with the new license that couldn't be the problem. 
Maybe it is helpful to update gurobi to the newest version? I'm sorry but I never had this error and can only guess what might help, and I use Anaconda so the setting on the server is different too. I remember that there are environment variables to set the path to gurobi, maybe something went wrong with them?

**Comment by ulfmueller** [comment]
We updated the solver (one of your wishes :wink: ) to the newest.  Weird, that you cannot enter gurobi.sh. I would have said, get a new license and everything should be fine. @MGlauer Could you please checkout the 'student' user and tweak it like you did it for the openego user? Or is it sth. we could do ourselves if you give us 'how-to' hints? 

@MarlonSchlemminger Sorry for the confusion!

**Comment by MarlonSchlemminger** [comment]
The grbgetkey command is not known either anymore on the server, so I am pretty sure it is the installation and not the license. Any news @ulfmueller  @MGlauer ?

**Comment by MarlonSchlemminger** [comment]
Fixed.
