### ISSUE TITLE
Load shedding analysis

### ISSUE THREAD

**Issue by lukasol** [openego/eTraGo#19]
work on https://github.com/openego/eTraGo/tree/features/load-shedding-analysis

- [x] one-year simulation in order to find all nodes with load shedding
- [x] discuss solutions: could we improve the subgrid connection if this is the reason

**Comment by ulfmueller** [comment]
I added a few lines which calculate and plot the total loadshedding per bus over the simulated timerange. see 937937117501b7753388e180942a946f03939334

@CaroDg Can you proceed?
I will start calculations for the entire year (via parallelisation) and then you can evaluate the buses where it happens...

**Comment by ulfmueller** [comment]
The analysis of the one-year simulation shows that 127 out of 11309 nodes show some load shedding. 
[This image](https://github.com/openego/eTraGo/files/1225026/loadshedding.pdf) gives you an impression about absolute load shedding and their regional distribution. How do we proceed? What are our options?
- check out manually the 127 nodes and their surroundings 
- #31 
- improve osmTGmod's subgrid algorithms
- ...

Right now I prefer the #31solution. But we would have to think about the details like 'how many' and which lines we would set to be extendable.

**Comment by lukasol** [comment]
I also prefer #31. It seems absolutely obvious that load_shedding (almost) only occurs in urban areas with quite weak mapping coverage. Subgrid function is in my eyes quite hard to modify and would in the best case result in the same as automatically extending the lines: with having no load_shedding left.

**Comment by ulfmueller** [comment]
we decided to try out the #31 . Therefore the following discussion takes place there.
