### ISSUE TITLE
K-means-clustering reduces available energy of variable carriers

### ISSUE THREAD

**Issue by MarlonSchlemminger** [openego/eTraGo#190]
When using k-means-clustering, the total available energy of variable carriers (sum over p_max_pu*capacity for each generator) is smaller than in the original network. The total capacity is the same in both networks, which means that the p_max_pu-calculation seems to have an error. The biggest difference appears for wind onshore, where the available energy is 10% smaller after clustering. Could you give me a hint where the p_max_pu calculation during k-means-clustering takes place? I couldn't find it.

**Comment by BartelsJ** [comment]
Does it appear for all carriers? The p_max_pu should be adapted in this [function ](https://github.com/openego/PyPSA/blob/dev/pypsa/networkclustering.py#L68)as far as I know.

**Comment by MarlonSchlemminger** [comment]
I only tested it for scenario Status Quo in 0.4.1 so far. Run of river isn't affected, solar changes only marginally (0.1%), wind offshore 2.5% and wind onshore 10%. I will have a look at the function, thanks.

**Comment by MarlonSchlemminger** [comment]
I think I know why this happens, but please correct me if I missunderstood some steps in the process (this was the first time I looked into k-means-clustering in detail).

1. [Here](https://github.com/openego/eTraGo/blob/dev/etrago/cluster/networkclustering.py#L480), generators.weight is set to 1.
2. [Here](https://github.com/openego/PyPSA/blob/dev/pypsa/networkclustering.py#L74), the weighting which is later used for the p_max_pu aggregation is calculated, based on the number of generators with the same bus and carrier. This means if there are 2 generators with the same bus and carrier, each generator has a weighting of 0.5. 
3. [Here](https://github.com/openego/PyPSA/blob/dev/pypsa/networkclustering.py#L85-L92) the p_max_pu aggregation takes place based in the weighting from step 2. 

What goes wrong is that the capacity of the generators isn't considered. The weighting should not be 1/(number of generators with same bus and carrier), but capacity/(sum of capacity with same bus and carrier). Run of river isn't affected by this bug, because the p_max_pu profile is flat and there are no differences between different generators. Do you agree? I would open a branch to adjust it then.

**Comment by MarlonSchlemminger** [comment]
We probably only need to change a single word, [this line](https://github.com/openego/PyPSA/blob/dev/pypsa/networkclustering.py#L74) from 
`weighting = generators.weight.groupby(grouper, axis=0).transform(lambda x: (x/x.sum()).fillna(1.))`
to 
`weighting = generators.p_nom.groupby(grouper, axis=0).transform(lambda x: (x/x.sum()).fillna(1.))`

**Comment by BartelsJ** [comment]
Looks good to me! You are very welcome to test it in a corresponding branch. :+1:

**Comment by MarlonSchlemminger** [comment]
I pushed a [branch](https://github.com/openego/PyPSA/tree/k-means_weight_pnom) to our PyPSA fork. As I expected, changing the single word for the calculation of the weighting from weight to p_nom fixes it and the available energy in the clustered network is now the same as in the original network. I don't think this should have an effect on anything else, because the variable weighting is only used twice. One purpose is to calculate the new p_max_pu and the second one is [this line](https://github.com/openego/PyPSA/blob/k-means_weight_pnom/pypsa/networkclustering.py#L75), where p_nom_max is set to weighting. This doesn't really make sense to me anyways. If there are no objections, I will merge this into the dev.

**Comment by MarlonSchlemminger** [comment]
I assigned you to the pull request. I think the problem only appears from dataset 0.4.1 onwards, because the p_max_pu profiles were the same inside each technology for all generators of the technology before 0.4.1. If the p_max_pu profiles differ between generators though, you need to consider the capacity of the generators when aggregating them.

**Comment by ulfmueller** [comment]
Thx! Makes sense what you say. But I still have one thing in mind I want to check...

**Comment by ulfmueller** [comment]
I am struggling with the change because we set the 'weight' in our etrago function and then we would just not use this value anymore. Hence [this](https://github.com/openego/eTraGo/blob/dev/etrago/cluster/networkclustering.py#L480) or [that respectively](https://github.com/openego/eTraGo/blob/dev/etrago/cluster/networkclustering.py#L544) would just be neglected and therefore obsolete.

**Comment by MarlonSchlemminger** [comment]
What is the 'weight' good for, is it used for anything else? If not, it is obsolete.

**Comment by ulfmueller** [comment]
Since this 'weight' implementation is part of PyPSA I would prefer that we change our 'weight' in etrago and leave the PyPSA code as it is...

**Comment by MarlonSchlemminger** [comment]
Ah no I think I understand what you mean. I would change both lines you linked from 
`network.generators['weight'] = 1`
to 
`network.generators['weight'] = network.generators.p_nom`
and leave the PyPSA code as it is. This should be the same result. Right? I will tackle this tomorrow.

**Comment by ulfmueller** [comment]
yes. that should do it. Only that the 'weight' would be then no relative parameter which is a bit ugly.
It might be also worth thinking of additionally grouping over same p_max_pu shape besides the carrier and bus grouper. Then we would not throw together differently behaving generators. But that would minimize the reduction of complexity. That is probably not a really good idea. 

Btw: 
> One purpose is to calculate the new p_max_pu and the second one is [this line](https://github.com/openego/PyPSA/blob/k-means_weight_pnom/pypsa/networkclustering.py#L75), where p_nom_max is set to weighting.

p_nom_max is actually devided by the weighting. I think that would be ok with your change too.

Thanks for finding this problem which occurs due to the recently applied more sophisticated weather differentiation of the p_max_pus!

**Comment by MarlonSchlemminger** [comment]
Everything worked as expected and I assigned you to the new pull request. The available energy remains the same after clustering and the generator weight is equal to its p_nom. As you said, grouping by the same p_max_pu shape (which would mean by the same weather cell) would mean a pretty high minimum amount of clustered nodes and is not a good idea in my opinion.

**Comment by ulfmueller** [comment]
Thx! I approved the PR. Good job finding out about this and fixing it!
