### ISSUE TITLE
Deal with line aggregation of k-means and line expansion

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#197]
When optimizing line expansion the [k-means line aggregation](https://github.com/openego/PyPSA/blob/master/pypsa/networkclustering.py#L178) has to be checked and slightly adjusted.

Adjustments:

- [x] [Here](https://github.com/openego/PyPSA/blob/master/pypsa/networkclustering.py#L196),  if one of the lines within a cluster is extendable=True the linegroup has to be a True as well. 
- [x] Lines which are not set to be extendable, still need to get a s_nom_min = s_nom assignment ([see](https://github.com/openego/eTraGo/blob/dev/etrago/tools/extendable.py#L38))
- [x] [capital costs](https://github.com/openego/PyPSA/blob/master/pypsa/networkclustering.py#L197) are changed to a weighted average with this [PR](https://github.com/openego/PyPSA/pull/7)
- [x] further more this needs to be changed, that only the capital costs of the ones which are extendable should be taken into account.
- [x] Theses changes only apply if capital costs are applied before the clustering. see #183

**Comment by ClaraBuettner** [comment]
S_nom_min and s_nom_max is set for all lines and transformers in [this branch](https://github.com/openego/eTraGo/blob/feature/%23197/etrago/tools/extendable.py). 
The capital cost function needed to be changed, this is updated in the branch of the referenced pull request. 
Currently, it's assumed that clustering is applied after setting capital costs.

**Comment by ClaraBuettner** [comment]
This has been done in https://github.com/openego/eTraGo/pull/209 and https://github.com/openego/PyPSA/pull/7. Since the NEP-extendable scenarios are still visible when k mean clustering is applied last, this order was chosen.
