### ISSUE TITLE
plot_line_loading is not working properly

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#199]
The new line loading functionality has got problems with the weighting.

Moreover the link representation should be checked.

**Comment by ClaraBuettner** [comment]
In branch https://github.com/openego/eTraGo/tree/feature/fix_plot_line_loading the colorbar fits to line and link loading, so link loading is not over 100% anymore.

**Comment by ulfmueller** [comment]
#200 fixes this.
