### ISSUE TITLE
v.0.3 Release

### ISSUE THREAD

**Issue by lukasol** [openego/eTraGo#20]
Start: Monday, 17.7.
Finish: Thursday, 20.7.

Consider all Tickets with Milestone 0.2 and the update of higher resoluted weather data and wind power curves (redmine ticket 1070, 431)

**Comment by ulfmueller** [comment]
@lukasol checkout PR: https://github.com/openego/eTraGo/pull/28 and give your review. For me it works like that. I am not 100% sure if the solution with the function etrago() in the appl.py is the best - but it seems ok and eGo can use that function like planned...

**Comment by lukasol** [comment]
There will be a small Release 0.2 at 20.07.2017

All other open issues are migrated to Milestone Release 0.3

**Comment by lukasol** [comment]
The Release v.0.3 will take place at Friday, 08. September.

Please try to finish your development until then and merge the respective branches into dev by 12:00 h.

@ulfmueller @wolfbunke @IlkaCu @BartelsJ

**Comment by lukasol** [comment]
Hi team, 
please remember tomorrow's release plan (see above) and document your progress in all tickets referring to milestone Release v0.3. If something cannot be implemented for the release, please also document that and remove the assignment to the milestone.

**Comment by ulfmueller** [comment]
In some cases (e.g. #10 ),
the main work has been finished and already pushed to the dev (so it will be part of the release), but some task remain to be pending.
In these cases should we just remove the assignment to the milestone, even though parts have been realized within that milestone?

**Comment by lukasol** [comment]
In that case, please state in the comments that you contributed something to dev and then remove the Release tag.

**Comment by wolfbunke** [comment]
I removed #24 because I can not ensure to finishing it.

**Comment by IlkaCu** [comment]
Unfortunately I didn't manage to work on #22 due to the endless DP-debugging. I removed the milestone from this issue.

**Comment by lukasol** [comment]
Release 0.3 has just been successfully completed. Thanks to all of you for your contribution!

We switched several ToDos to an upcoming release, I think the project meeting is the right place to discuss how we proceed here.
