### ISSUE TITLE
kmean_clustering() returns clustering instead of network

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#214]
The kmean_clustering() since the disaggregation was merged into dev now returns [clustering](https://github.com/openego/eTraGo/blob/dev/etrago/cluster/networkclustering.py#L557) instead of network.
Does that have a reason or is that necessary for the disaggregation?
It changes the usage of the function slightly since like this the network is stored in clustering.network...

**Comment by wolfbunke** [comment]
something new?
