### ISSUE TITLE
Datav0.4.4 eGo100

### ISSUE THREAD

**Issue by BartelsJ** [openego/eTraGo#221]
Using the data set v0.4.4 I received following error for the eGo100 scenario. Any hints?

runfile('/home/jbartels/projekte/open-ego/eTraGo/etrago/appl.py', wdir='/home/jbartels/projekte/open-ego/eTraGo')
Reloaded modules: etrago, etrago.cluster, etrago.cluster.disaggregation, pypsa, pypsa.components, pypsa.descriptors, pypsa.io, pypsa.pf, pypsa.contingency, pypsa.opt, pypsa.opf, pypsa.plot, pypsa.graph, pypsa.networkclustering, pypsa.geo, etrago.cluster.networkclustering, etrago.tools, etrago.tools.utilities, egoio, egoio.db_tables, egoio.db_tables.model_draft, etrago.tools.io, etrago.tools.plot, etrago.tools.extendable, etrago.cluster.snapshot, egoio.tools, egoio.tools.db, egoio.db_tables.grid
2018-08-24 08:45:36.709315
No data for GeneratorPqSet in column p_set.
Series p_set of component Generator could not be imported
No data for GeneratorPqSet in column p_max_pu.
Series p_max_pu of component Generator could not be imported
No data for LoadPqSet in column p_set.
Series p_set of component Load could not be imported
No data for LoadPqSet in column q_set.
Series q_set of component Load could not be imported
No data for StoragePqSet in column p_set.
Series p_set of component StorageUnit could not be imported
WARNING:pypsa.components:The bus name `23648` given for bus0 of Transformer `nan` does not appear in network.buses
WARNING:pypsa.components:The bus name `16573` given for bus1 of Transformer `nan` does not appear in network.buses
WARNING:pypsa.components:The bus name `16573` given for bus0 of Line `nan` does not appear in network.buses
WARNING:pypsa.components:The bus name `28353` given for bus1 of Line `nan` does not appear in network.buses
Traceback (most recent call last):

  File "<ipython-input-2-a894517d1f07>", line 1, in <module>
    runfile('/home/jbartels/projekte/open-ego/eTraGo/etrago/appl.py', wdir='/home/jbartels/projekte/open-ego/eTraGo')

  File "/home/jbartels/miniconda3/envs/julian/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "/home/jbartels/miniconda3/envs/julian/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/jbartels/projekte/open-ego/eTraGo/etrago/appl.py", line 576, in <module>
    network, disaggregated_network = etrago(args)

  File "/home/jbartels/projekte/open-ego/eTraGo/etrago/appl.py", line 383, in etrago
    network =  add_missing_components(network)

  File "/home/jbartels/projekte/open-ego/eTraGo/etrago/tools/utilities.py", line 982, in add_missing_components
    add_110kv_line("16573", "28353")

  File "/home/jbartels/projekte/open-ego/eTraGo/etrago/tools/utilities.py", line 946, in add_110kv_line
    pypsa.geo.haversine(network.buses.loc[bus0, ["x", "y"]],

  File "/home/jbartels/miniconda3/envs/julian/lib/python3.6/site-packages/pandas/core/indexing.py", line 1325, in __getitem__
    return self._getitem_tuple(key)

  File "/home/jbartels/miniconda3/envs/julian/lib/python3.6/site-packages/pandas/core/indexing.py", line 836, in _getitem_tuple
    return self._getitem_lowerdim(tup)

  File "/home/jbartels/miniconda3/envs/julian/lib/python3.6/site-packages/pandas/core/indexing.py", line 967, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)

  File "/home/jbartels/miniconda3/envs/julian/lib/python3.6/site-packages/pandas/core/indexing.py", line 1551, in _getitem_axis
    self._has_valid_type(key, axis)

  File "/home/jbartels/miniconda3/envs/julian/lib/python3.6/site-packages/pandas/core/indexing.py", line 1442, in _has_valid_type
    error()

  File "/home/jbartels/miniconda3/envs/julian/lib/python3.6/site-packages/pandas/core/indexing.py", line 1429, in error
    (key, self.obj._get_axis_name(axis)))

KeyError: 'the label [16573] is not in the [index]'

**Comment by ulfmueller** [comment]
What are your args? I have no troubles running calculations on 044 and eGo 100.

**Comment by BartelsJ** [comment]
Hm, strange. I used the following arguments. Interestingly, NEP 2035 and Status Quo are ok.. if you do not receive this failure, I have to check my package settings..

args = {  # Setup and Configuration:
    'db': 'oedb',  # database session
    'gridversion': 'v0.4.4',  # None for model_draft or Version number
    'method': 'lopf',  # lopf or pf
    'pf_post_lopf': False,  # perform a pf after a lopf simulation
    'start_snapshot': 1,
    'end_snapshot': 2,#3049,#8760,
    'solver': 'cplex',  # glpk, cplex or gurobi
    'solver_options': {'threads':4, 'lpmethod':4, 'solutiontype':2, 
                       'barrier convergetol':1.e-5,
                       'network tolerances feasibility':1.e-5,},  # {} for default or dict of solver options
    'scn_name': 'eGo100',  # a scenario: Status Quo, NEP 2035, eGo100
    # Scenario variations:
    'scn_extension': None,  # None or array of extension scenarios
    'scn_decommissioning':None, # None or decommissioning scenario
    # Export options:
    'lpfile': False,  # save pyomo's lp file: False or /path/tofolder
    'results': False,# save results as csv: False or /path/tofolder
    'export': False,  # export the results back to the oedb
    # Settings:
    'extendable': [],#['storages'],  # Array of components to optimize
    'generator_noise': 789456,  # apply generator noise, False or seed number
    'minimize_loading': False,
    # Clustering:
    'network_clustering_kmeans': False,#100,  # False or the value k for clustering
    'load_cluster': False,#'./cluster_coord_k_100_result',  # False or predefined busmap for k-means
    'network_clustering_ehv': False,  # clustering of HV buses to EHV buses.
    'disaggregation': None, # or None, 'mini' or 'uniform'
    'snapshot_clustering': False,  # False or the number of 'periods'
    # Simplifications:
    'parallelisation': False,  # run snapshots parallely.
    'skip_snapshots': False,
    'line_grouping': False,  # group lines parallel lines
    'branch_capacity_factor': 0.7,  # factor to change branch capacities
    'load_shedding': False,  # meet the demand at very high cost
    'comments': None}

**Comment by ClaraBuettner** [comment]
The add_missing_components functions adds lines in Munich and Stuttgart manually and is not usable for SH-Scenarios. I could implement that it is only applied if the scenario contains the whole network. 
Have you already tried to choose 'eGo 100' instead of 'eGo100'?

**Comment by BartelsJ** [comment]
Thank you very much for the hints, Clara! It works with 'eGo 100' instead of 'eGo100' and I see the point concerning SH scenarios.
