### ISSUE TITLE
Snapshot clustering using generator.p_set instead of generator.p_max_pu

### ISSUE THREAD

**Issue by OriolRaventos** [openego/eTraGo#242]
If one wants to perform the lopf, the relevant time series aggregation to cluster are the generator.p_max_pu. That is the ones that have a role in the PyPSA opf.py file.

Also the p_max_pu have the advantage of being normalized already.

As a side comment, I decided to normalize the load data a well (although I believe that the tsam package does that by itself anyway).

**Comment by ClaraBuettner** [comment]
Since etrago 0.7.1. snapshot clustering uses p_max_pu * p_nom instead of p_max_pu:
https://github.com/openego/eTraGo/blob/1aa57e9b560d309eb6c5af019aad9ef77a6d1be5/etrago/cluster/snapshot.py#L212-L214
Can we close this issue?
