### ISSUE TITLE
AttributeError in etrago.tools.plot.plot_residual_load(network)

### ISSUE THREAD

**Issue by wolfbunke** [openego/eTraGo#254]
By testing all plotting functions of eTraGo in eGo I got an "AttributeError: 'DataFrame' object has no attribute 'former_dispatch'" by using etrago.tools.plot.plot_residual_load(network).

The missing attribute  "former_dispatch" or "dispatch" (older version)  is defined in:

- https://github.com/openego/eTraGo/blob/bfbb9b853664075004b1d5082a4602630d833a65/etrago/tools/io.py#L337
- https://github.com/openego/eTraGo/blob/bfbb9b853664075004b1d5082a4602630d833a65/etrago/tools/io.py#L381

and used in:

- https://github.com/openego/eTraGo/blob/1751488702d4520f5154c7629d68ad6d4eef1d76/etrago/tools/plot.py#L731

Looking at the components "former_dispatch" is not displayed in: 

- https://github.com/openego/PyPSA/blob/master/pypsa/component_attrs/generators.csv

Could this maybe cause this Error?

**Comment by ClaraBuettner** [comment]
Yes, I think that's why the attribute is missing in eGo.
I just checked the plot in eTraGo and it's not working properly  because former_dispatch is missing after k_means_clustering. So I suggest to update the plotting function and not the generators.csv.

**Comment by ClaraBuettner** [comment]
This is fixed in [this](https://github.com/openego/eTraGo/pull/258/commits/d78ab5daa57da646306c4e7c984952ef0bc50c8e) PR.
