### ISSUE TITLE
Add setup.py for pip install

### ISSUE THREAD

**Issue by mariusves** [openego/eTraGo#26]
To be able to install eTraGo a setup.py is needed. Also certain parts in the modules as well as the appl.py have to be adjusted.

**Comment by wolfbunke** [comment]
Nice, I placed also a setup see: https://github.com/openego/eTraGo/blob/features/etrago-function/setup.py but at the moment it is still work in progress. I will wait until your a done, thx

**Comment by mariusves** [comment]
Just after I uploaded my setup.py I saw your comment as well as your setup.py . 
Are all these requirements necessary? I would think that they are covered already by ego.powerflow and ego.io?

**Comment by wolfbunke** [comment]
oh yes, I think your right!

**Comment by mariusves** [comment]
added via b9778e4

**Comment by ulfmueller** [comment]
@mariusves Could you edit the readme so one knows that it is possible/necessary to install via pip:
sudo pip3 install -e path
similar to the readme of the [data processing](https://github.com/openego/data_processing/blob/master/README.md)
?
