### ISSUE TITLE
network_clustering_ehv bug

### ISSUE THREAD

**Issue by OriolRaventos** [openego/eTraGo#282]
Running the appl.py with ```gridversion: 'v0.4.5'```, ```scn_name: 'NEP 2035'```  and ```network_clustering_ehv: 'True'``` produces an error because two manually added transformers '23009' and '99999' have v_nom0 > v_nom1. That is an issue, because networkclustering.py just checks if v_nom0 = 110:

https://github.com/openego/eTraGo/blob/e72ed73a4231d6c2f31e72a442078874d9b38a00/etrago/cluster/networkclustering.py#L105-L108

it can be solved just swapping the columns of the transformers appropriately:

```
    aux=np.where(network.transformers.v_nom0 < network.transformers.v_nom1, \
                 [network.transformers.v_nom0,network.transformers.v_nom1, \
                  network.transformers.bus0,network.transformers.bus1], \
                  [network.transformers.v_nom1,network.transformers.v_nom0, \
                  network.transformers.bus1,network.transformers.bus0])
    network.transformers['v_nom0']=aux[0]
    network.transformers['v_nom1']=aux[1]
    network.transformers['bus0']=aux[2]
    network.transformers['bus1']=aux[3]
```

or changing the networkclustering.py so that it checks also v_nom1.

Potentially, it could be yet another problem, due to a bug in graph.py from PyPSA v0.11fork, which was subsequently corrected:

https://github.com/PyPSA/PyPSA/blob/8d6bb33f12d2d2677fd4e6a6afdf3b3cfb270508/pypsa/graph.py#L101

for 

https://github.com/PyPSA/PyPSA/blob/39ad432e1b19758cd259bed334db9c428385c5e9/pypsa/graph.py#L139

but this only shows up in case we do not read the busmap from psql I believe.

**Comment by ClaraBuettner** [comment]
This problem was fixed in the current dev-branch with #264. The buses of transformers where v_nom0 > v_nom1 are swapped: 
https://github.com/openego/eTraGo/blob/f7300801c0eff1ffb2b83268369059c4a7c0e1bd/etrago/tools/utilities.py#L1374-L1381
