### ISSUE TITLE
pip dependency links are deprecated

### ISSUE THREAD

**Issue by birgits** [openego/eTraGo#286]
Maybe you are already aware of it but as of pip 0.19.0 installation using dependency links is deprecated wherefore the installation of eTraGo fails. Adding `'pypsa @ git+https://github.com/openego/PyPSA.git@master#egg=pypsa-0.11.0fork'` to install_requires in setup.py and deleting the dependency_links fixes this.

**Comment by ClaraBuettner** [comment]
With PR #302 we don't need the pypsa fork anymore, so this is problem is fixed.
