### ISSUE TITLE
Decomission nep2035_b2 leaves some isolated buses

### ISSUE THREAD

**Issue by OriolRaventos** [openego/eTraGo#287]
Using v0.4.5 of NEP3050 with extensions nep2035_b2 and BE_NO_NEP 2035 and decommission  nep2035_b2 I get 71 isolated (no line, no link and no transformer connection) buses:

[ 9562,   825,   824,    43,    41, 11159, 11158,    34,  1568,
       11324,  1567,  8367, 11325,  1566,    40, 13326,    44,    45,
        8364,  1759,  5972, 11250, 11253, 11951,   109,  1761, 11249,
       11535, 11950, 11537, 11949,  8750, 11534, 11947,  8751,   442,
        5367,  8745,  5364,  1749,  8746,  8749,  4106,  8719,  8892,
        4448,  9337,  8891,   409,   397,   280,  7673,   259,   398,
         261,   396,   284, 13110,   895, 14067, 13109,   894, 13108,
         896,   897, 14063, 26946, 26703, 10121,  2189, 10303]

from which there are 2 buses with loads: 26946 and bus 26703, and 29 generators. Many other (I guess) are just old artificial buses related to transformers.

The problem is that the decommission function 

https://github.com/openego/eTraGo/blob/f7300801c0eff1ffb2b83268369059c4a7c0e1bd/etrago/tools/io.py#L766

just drops lines without checking is some "important" bus is left isolated.

**Comment by ClaraBuettner** [comment]
I just checked this problem but couldn't reproduce it. Can you tell me which branch and settings you use? 

> The problem is that the decommission function just drops lines without checking is some "important" bus is left isolated.

Yes that's true, it's not checked in etrago, but it is part of the scenario creation in the dataprocessing.

**Comment by OriolRaventos** [comment]
I used eTraGo version 0.7.1 and the arguments:

args = {
    # Setup and Configuration:
    'db': 'oedb',  # database session
    'gridversion': 'v0.4.5',  # None for model_draft or Version number
    #'v0.2.11' for SH scenarios
    'method': 'lopf',  # lopf or pf
    'pf_post_lopf': False,  # perform a pf after a lopf simulation
    'start_snapshot': 1, #Starting at 1
    'end_snapshot': 8760, #Ending at 8760
    'solver': 'gurobi',  # glpk, cplex or gurobi
    'solver_options': {'BarConvTol': 1.e-5, 'FeasibilityTol': 1.e-5,
                       'logFile': 'solver.log'},  # {} for default options
    'scn_name': 'NEP 2035',  # a scenario: Status Quo, NEP 2035, eGo 100
    #or SH Status Quo, SH NEP 2035
    # Scenario variations:
    'scn_extension': ["nep2035_b2", "BE_NO_NEP 2035"],  # None or array of extension scenarios
    #'nep2035_confirmed', 'nep2035_b2', 'BE_NO_NEP 2035'
    'scn_decommissioning': "nep2035_b2",  # None or decommissioning scenario
    #'nep2035_confirmed', 'nep2035_b2'
    # Export options:
    'lpfile': False,  # save pyomo's lp file: False or /path/tofolder
    'csv_export': '/home/raventos/paper/Data',  # save results as csv: False or /path/tofolder
    'db_export': False,  # export the results back to the oedb
    # Settings:
    'extendable': ['network', 'storage'],  # Array of components to optimize
    'generator_noise': 789456,  # apply generator noise, False or seed number
    'minimize_loading': False,
    'ramp_limits': False,  # Choose if using ramp limit of generators
    'extra_functionality': None,  # Choose function name or None
    # Clustering:
    'network_clustering_kmeans': False,#300,  # False or the value k for clustering
    'load_cluster': False,  # False or predefined busmap for k-means
    'network_clustering_ehv': False,  # clustering of HV buses to EHV buses.
    'disaggregation': None,  # None, 'mini' or 'uniform'
    'snapshot_clustering': False,  # False or the number of 'periods'
    # Simplifications:
    'parallelisation': False,  # run snapshots parallely.
    'skip_snapshots': False,
    'line_grouping': False,  # group lines parallel lines
    'branch_capacity_factor': {'HV': 1.0, 'eHV': 1.0}, # {'HV': 0.5, 'eHV': 0.7},  # p.u. branch derating
    'load_shedding': False,  # meet the demand at value of loss load cost
    'foreign_lines': {'carrier': 'AC', 'capacity': 'osmTGmod'}, # could be 'DC' and 'ntc_acer' or 'thermal_acer'
    'comments': None}

**Comment by ClaraBuettner** [comment]
I still can't reproduce this problem. Looking at the position of the buses you mentioned (shown in red) they don't seem to be close to decomissioned lines (shown in green) in version v0.4.5:
![Bildschirmfoto vom 2020-06-04 17-36-55](https://user-images.githubusercontent.com/22964326/83778040-73664000-a68a-11ea-8983-06b43b605ec2.png)
There have been some changes in version v0.4.6 concerning extension and decomissiong scenarios. Do you get the same error when using this version?

**Comment by OriolRaventos** [comment]
I spent some time looking at it again and I downloaded the version v0.4.6. This version does not have any isolated buses. Hence I am closing this Issue. For completeness, I examined again the version v0.4.5 that I have and the isolated points seem to be related to end points connected to the grid by transformers that were missing.

I also double checked that Issue https://github.com/openego/eTraGo/issues/288#issue-614749890 is not happening again with v0.4.6, so there is nothing missing as far as I can see. Nevertheless, as you mention there, there is still the following error message:

> No data for StoragePqSet in column p_set.
> Series p_set of component StorageUnit could not be imported
> No data for GeneratorPqSet in column p_set.
> Series p_set of component Generator could not be imported
> No data for GeneratorPqSet in column p_max_pu.
> Series p_max_pu of component Generator could not be imported
> No data for LoadPqSet in column p_set.
> Series p_set of component Load could not be imported
> No data for LoadPqSet in column q_set.
> Series q_set of component Load could not be imported
> No data for StoragePqSet in column p_set.
> Series p_set of component StorageUnit could not be imported
> ERROR:pypsa.io:Error, new components for Carrier are not unique
> No data for StoragePqSet in column p_set.
> Series p_set of component StorageUnit could not be imported
> ERROR:pypsa.io:Error, new components for Carrier are not unique

**Comment by OriolRaventos** [comment]
Although the issue is closed, I just wanted to leave a comment here maybe for future use. Those buses that seemed to be isolated in the old version (shown on the map above), are end buses connected to transformers. What happens after the extension / decommission is that some of this transformers connects nodes that are up to 36 kilometers apart. That does not happen in the non-extended models (all the transformers connect nodes in the very same position except for 2 that are just few meters apart).

**Comment by ClaraBuettner** [comment]
These transformers do not represent existing components but are needed to connect buses from decommissioned lines to the next ehv-bus. When 110kV lines are decommissioned, the distance to the next ehv-bus can be longer, but 36 km seem to be a very long distance. I can take a closer look at these transformers. 
By contrast, in the original grid model (the non-extended model) transformers represent real components, so they don't have a length.
