### ISSUE TITLE
Make use of new export2db feature of ego.powerflow

### ISSUE THREAD

**Issue by mariusves** [openego/eTraGo#29]
For the new export2db feature of ego.powerflow everything is prepared.
For testing check out the following branches:
https://github.com/openego/eTraGo/tree/feature/add-export2db
https://github.com/openego/ego.io/tree/features/add-pf-result-tables
https://github.com/openego/ego.powerflow/tree/features/add-export2db
https://github.com/openego/data_processing/tree/features/add-pf-result2db

The new result tables are not yet in the oedb, will do that in a moment.

**Comment by lukasol** [comment]
This has been added to the release. @mariusves  has it been tested?

**Comment by mariusves** [comment]
This has been tested for several different settings, apart from network_clustering, since that feature somehow failed to work on my end (probably my fault). But I think that it should not cause any issues.

**Comment by lukasol** [comment]
There was a bug with the network clustering, but it should be working by now. Thanks!
