### ISSUE TITLE
Release 0.8

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#292]
- [x] update to the newest pypsa version 0.17

- [x] check if pypsa fork is still a useful environment or if we can directly use pypsa 0.17

- [x] think if structural changes to object-oriented programming might be worth its benefits (e.g. inheritance from pypsa)

- [x] check which etrago-functions can be replaced by existing pypsa functions (e. g. ilopf (pypsa) vs. iterate_lopf (etrago)

- [x] update etrago functions to newer packages (e.g. pandas 1.0.2)

**Comment by ClaraBuettner** [comment]
I think we should check which etrago-functions could be replaced by existing pypsa functions.

Besides, if we change etrago to more object-oriented programming we could inheritance from pypsa and would have the possibility to overwrite pypsa-functions. So we could adjust pypsa without a fork. I know this needs a lot of structural changes. It's just an idea.

**Comment by ulfmueller** [comment]
I agree! just to have a better overview of the tasks, can you add them to the checklist?

**Comment by ulfmueller** [comment]
i created a new milestone to tag our issues. I would say the goal for the new milestone is a first working sector model.

**Comment by ClaraBuettner** [comment]
With pypsa 0.17.1 we can get rid of pypsa-fork as described here: #101
