### ISSUE TITLE
pyutilib 6.0 does not include enum anymore, going back to 5.8.0 fixes the issue

### ISSUE THREAD

**Issue by viole-i** [openego/eTraGo#299]
During the installation of eTraGo with pip install -e eTraGo today, I got this error:

> File ".../lib/python3.6/site-packages/pyomo/opt/base/formats.py", line 16, in <module>
> from pyutilib.enum import Enum
>   File ".../lib/python3.6/site-packages/pyutilib/enum/__init__.py", line 18, in <module>
>     package) that supersedes this library.""")
> ImportError: pyutilib.enum has been removed.
> 
> Python 3 now has an enum implementation in the standard library (also
> available for older Python versions as the third-party enum34 PyPI
> package) that supersedes this library.

When I changed the file formats.py from
> from pyutilib.enum import Enum

to
> from enum import Enum

I ran into the error:

> File ".../lib/python3.6/site-packages/pyomo/opt/base/formats.py", line 34, in <module>
>     ProblemFormat = Enum('colin', 'pyomo', 'cpxlp', 'nl', 'mps', 'mod', 'lpxlp', 'osil', 'colin_optproblem', 'FuncDesigner','bar','gams')
> TypeError: __call__() takes from 2 to 3 positional arguments but 13 were given

Quick fix for this: Changing the installed pyutilib version to 5.8.0 (the newest version I had was 6.0)
> pip install pyutilib==5.8.0

**Comment by ClaraBuettner** [comment]
This error will be fixed when we use the newest pypsa version in the next release. But for the current dev, changing the pyutilib version is needed, so I leave this issue open until the next release. 
Thanks for reporting and fixing the error!

**Comment by ClaraBuettner** [comment]
This was fixed in PR #302
