### ISSUE TITLE
Test load flow formulation method

### ISSUE THREAD

**Issue by lukasol** [openego/eTraGo#3]
Apart from default 'angles' method other methods like 'kirchhoff', 'cycles' or 'ptdf' should be tested in order to find ways to reduce computation time.

**Comment by lukasol** [comment]
There will be an extensive documentation on the solvers and formulation methods by Milestone Release 0.3

**Comment by BartelsJ** [comment]
Several solvers, formulation methods and szenarios were tested with respect to computation time. Tendency of gurobi/angles for small systems (~federal states) and cplex/angles for greater systems (~countries). Results are documented [here](http://oep.iks.cs.ovgu.de/redmine/projects/open_ego/wiki/Performance_verschiedener_Solver_und_LOPF-Formulierungen_in_eTraGo_(AP_34)).
