### ISSUE TITLE
Implementation of adjacent snapshotclustering

### ISSUE THREAD

**Issue by wheitkoetter** [openego/eTraGo#301]
Isabelle Viole (DLR) implemented the adjacent snapshot clustering, as part of her master thesis. The full version of the developed code and the results are stored locally at DLR. As not all parts of the code were relevant for implementation in etrago, Wilko created a cleaned version of isabelles code in the branch [feature/segmentation_for_dev](https://github.com/openego/eTraGo/tree/feature/segmentation_for_dev).

**Comment by AmeliaNadal** [comment]
https://github.com/openego/eTraGo/pull/342
