### ISSUE TITLE
add p2g as an extendable option

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#346]

**Comment by ulfmueller** [comment]
@AmeliaNadal 

1.  I would 'switch on' investment optimization of p2g and g2p plants in etrago just like in the other cases of such optimization (network, storage units...). So you can restrain from setting p_nom_extendable to True already in eGon-data
2. So far there are no (possible) power-to-H2 plants in the data model, only the other way around, right? Will this be added or is it a one-way modelling?

**Comment by fwitte** [comment]
Hi @ulfmueller,

on https://github.com/openego/eGon-data/pull/478 all H2 related technologies for eGon2035 are inserted. Assumptions for capital and marginal costs as well as efficiency values will be updated in a different PR to remove the hard coded data.

**Comment by ulfmueller** [comment]
Nice! Then this will come in that PR :) Any ideas, when it'll be merged? As one minor change, I would suggest that you do not set p_nom_extendable to a value resp. nan (or to false). Then we can switch it on in etrago. Then it is consistent to the other components to be optimized in terms of investment. ok?

**Comment by ulfmueller** [comment]
ok, we talked about this again and we would propose that we consistently set the p_nom_extendable or s_nom_extendable as we want to have it in our 'base-case' modelling. Hence, you can leave it as it is (p_nom_extendable = True) and we will adjust the data model in the other cases (e.g. grid, storage_units). eTraGo will be changed accordingly - in a suitable way (I will create an issue for that)...
