### ISSUE TITLE
change the extendable design

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#348]
So far, all the components you want to optimize investment-wise have to be called in the args, [here](https://github.com/openego/eTraGo/blob/dev/etrago/appl.py#L76) according to the possible parameters which will be processed in this [extendable function](https://github.com/openego/eTraGo/blob/dev/etrago/tools/extendable.py#L45)

The future data model will have, in a base-setting, already 'turned on' p_nom_extendable/s_nom_extendable (=True). Therefore the function shall be rewritten such that once a component which is optimized by default is called in the args, will take the True from the data model and once it is not mentioned in the args it has to be set to false. In addition, alternative optimizing strategies can be defined...

**Comment by ulfmueller** [comment]
I would implement it as follows:

- we create an attribute called like "defined-by-db". Then everything will be optimized as it is set at the database level. no s_nom_extendable values (or similar) will be altered at app-level.
- If that attribute is not set but instead s.th. like ["german_network"] then all extendables will be set to false instead of the german network lines. The specific assumptions in the db would be overwritten.
- If a combination of both is given like ["defined-by-db", "foreign_network"]. Then the setting from the db is set and then altered (if necessary) as stated by the other attributes. In this example the foreign_network lines would be extendable (in contrast to the current db setting) and all the other components will be optimized as set in the data base.

@ClaraBuettner what do you think? Do you agree?

**Comment by ClaraBuettner** [comment]
> I would implement it as follows:
> 
>     * we create an attribute called like "defined-by-db". Then everything will be optimized as it is set at the database level. no s_nom_extendable values (or similar) will be altered at app-level.
> 
>     * If that attribute is not set but instead s.th. like ["german_network"] then all extendables will be set to false instead of the german network lines. The specific assumptions in the db would be overwritten.
> 
>     * If a combination of both is given like ["defined-by-db", "foreign_network"]. Then the setting from the db is set and then altered (if necessary) as stated by the other attributes. In this example the foreign_network lines would be extendable (in contrast to the current db setting) and all the other components will be optimized as set in the data base.
> 
> 
> @ClaraBuettner what do you think? Do you agree?

I agree! 
It might make sense to somehow document which components are extendable in 'defined-by-db'. Maybe we can also refer to the documentation of eGon-data, I will have a looks if its already documented there.
