### ISSUE TITLE
Make the clustering of the buses abroad optional

### ISSUE THREAD

**Issue by AmeliaNadal** [openego/eTraGo#364]
Currently, the clustering of all the sectors is including the buses abroad, except for the gas sector (not yet in dev, see https://github.com/openego/eTraGo/pull/359), for which the buses abroad are excluded.
As both options could make sense, this could be an option to be set in the parameters to cluster the buses abroad or keep them out of the clustering.

**Comment by pieterhexen** [comment]
**Details**
https://github.com/openego/eTraGo/blob/c3f73c246296f488d3567cdb1d8970f3bd920ecf/etrago/appl.py#L79
will refer to the number of resulting clusters in the specified scope (_only DE_ or _all countries_). This results in the following behaviour:  
- with 'n_clusters_gas' set to 12 and clustering only in DE a total of 24 buses will be created: 12 buses in DE and 12 foreign buses (FR, UK etc.) 
- with 'n_clusters_gas' set to 12 and clustering enabled for all countries a total of 12 buses will be created.

Need to find a good way to document this.

**Comment by pieterhexen** [comment]
Featue was inplemented in #425
