### ISSUE TITLE
Update pf_post_lopf for sector coupled model

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eTraGo#370]
The `pf_post_lopf` is not converging in eTraGo when the sector-coupled model is used. The error is `NaN` and no iteration is successful, so it seems to be a structural problem.

**Comment by CarlosEpia** [comment]
@birgits asked about the reactive power for CHP plants. After checking some papers I concluded that they can be used to provide ancillary services (voltage control), but under the assumption that its generation schedule can not be modified (reactive power can be produced just when the CHP is supposed to supply active power).
https://dspace.mit.edu/bitstream/handle/1721.1/126901/1191623094-MIT.pdf?sequence=1&isAllowed=y
