### ISSUE TITLE
sub_networks

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#375]
We have now plenty of sub_networks in our systems due to e.g. the heat stuff which is not interconnected and of a different carrier than AC. So far, in the dev, there are also plenty of sub_networks with the carrier 'CH4' and 'H2_grid'. That does not make sense, does it @AmeliaNadal ? I would expect it to be one sub_network and not several...

**Comment by AmeliaNadal** [comment]
No you're fully right, it doesn't seems to make sense, I will have a look.

**Comment by AmeliaNadal** [comment]
The sub_networks are first created in the kmean_clustering, by the call of [get_clustering_from_busmap](https://github.com/openego/eTraGo/blob/a114a04fa764f95321f846b504c718c3a6441e45/etrago/cluster/networkclustering.py#L853),
and more precisely in the call of [determine_network_topology()](https://github.com/PyPSA/PyPSA/blob/master/pypsa/networkclustering.py#L334) (determine_network_topology() is also called later in the [gas_clustering](https://github.com/openego/eTraGo/blob/dev/etrago/cluster/gasclustering.py#L383)).
I guess, that the "disconnected buses" are identified in [these lines](https://github.com/PyPSA/PyPSA/blob/master/pypsa/components.py#L1090:#L1092) of the the determine_network_topology() definition, but I wasn't able to determine why exactly buses are disconnected or not: all the non AC buses are "disconnected" buses, but some AC buses too.

**Comment by AmeliaNadal** [comment]
In the PyPSA definition of [sub-network](https://pypsa.readthedocs.io/en/latest/components.html#sub-network), `Sub-networks are subsets of buses and passive branches (i.e. lines and transformers) that are connected. [...] Only “AC” and “DC” sub-networks can contain passive branches; all other sub-networks must contain a single isolated bus.`.
This is then normal that there are plenty of sub_networks with the carrier 'CH4' and 'H2_grid'.
@ulfmueller, do you see it as an issue or could we let it like it is?

**Comment by ClaraBuettner** [comment]
Can we close this issue?
