### ISSUE TITLE
More CH4 buses in the neighboring countries after kmeans electricity than originally in db

### ISSUE THREAD

**Issue by fwitte** [openego/eTraGo#397]
On the ci dump from 28.02. there are 12 CH4 buses in foreign countries in the eGon2035 scenario. After electricity clustering and before gas clustering starts, there are 24 CH4 buses in the foreign countries. Anyone an idea, how this happens?

[CH4_buses_db.csv](https://github.com/openego/eTraGo/files/8322136/CH4_buses_db.csv)
[CH4_buses_after_kmeans_el.csv](https://github.com/openego/eTraGo/files/8322137/CH4_buses_after_kmeans_el.csv)

**Comment by fwitte** [comment]
The buses are just outside or inside the vg250 boundaries:

![grafik](https://user-images.githubusercontent.com/20252362/159641427-3fa36dd1-e4f4-4cc7-a51d-03182ffe1b72.png)

@CarlosEpia, do you have an idea? We can put this on our agenda for later as well!

**Comment by CarlosEpia** [comment]
Hi @fwitte. Sure, we can discuss also this topic during our meeting in the afternoon. Could you please run the SH test case to see if something similar is happening there? I just tried and the number of buses does not change in my case.

**Comment by fwitte** [comment]
No, does not happen in SH case. There are no CH4 buses as near to the borders as in Germany case.

**Comment by CarlosEpia** [comment]
If the problem is related to buses close to the borders, it is most likely due to the resolution of the shapefile we use to assign the country to each bus. see https://github.com/openego/eTraGo/issues/356. We can find an alternative to it in the afternoon.

**Comment by CarlosEpia** [comment]
Can we meet here? 
https://meet.jit.si/ego_n-project_hsfl

**Comment by CarlosEpia** [comment]
The function "buses_by_country" in utilities.py was improved to deal with this problem. Now it uses the German borders available in egon-data. It looks like everything is working ok, but there are 2 CH4 buses (37764 and 38215) that are labeled as located in Germany but this does not match our geodata. Therefore, after the k-mean clustering, the number of CH4 buses in neighboring countries increased from 12 to 14.
![Screenshot from 2022-03-25 11-32-51](https://user-images.githubusercontent.com/62600091/160104520-cb8fee91-0392-4a68-8a53-c636007b54fc.png)
![Screenshot from 2022-03-25 11-33-43](https://user-images.githubusercontent.com/62600091/160104670-d9b6e6e3-3ac9-4726-9498-86685a0f058d.png)
Would it be an option to relocate those buses in egon-data to avoid this problem?

**Comment by CarlosEpia** [comment]
Hi @fwitte according to our meeting this morning, I checked and found out that the pypsa functions "aggregatebuses"
https://github.com/openego/eTraGo/blob/c667fc7032505ec463bc709d244ecd030d7ce1c4/etrago/cluster/networkclustering.py#L394-L398
and  "get_clustering_from_busmap"
https://github.com/openego/eTraGo/blob/c667fc7032505ec463bc709d244ecd030d7ce1c4/etrago/cluster/networkclustering.py#L980-L988
delete the country column of the buses tables after they are executed.

**Comment by fwitte** [comment]
This should be fixed, or?
