### ISSUE TITLE
Add e-moility carriers to clustering functions

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eTraGo#415]
The most recent egon-data backup includes e-mobility data. This currently leads to problems in the clustering because the carriers are not included in the functions yet. 
@CarlosEpia: Could you maybe have a look at this?

**Comment by CarlosEpia** [comment]
> The most recent egon-data backup includes e-mobility data. This currently leads to problems in the clustering because the carriers are not included in the functions yet. @CarlosEpia: Could you maybe have a look at this?

Sure. I will manage this today.
