### ISSUE TITLE
Dependency missing in setup.py: cartopy

### ISSUE THREAD

**Issue by fwitte** [openego/eTraGo#426]
9bb242516462ef7bab5c8361d65b1f4c7e86817c brought cartopy in the dependencies, but it is not yet included in setup.py

**Comment by ClaraBuettner** [comment]
The installation of `cartopy` could be a bit complicated and you also need to install system-wide packages. 
The tool is only used for background maps in plots. We could also make the usage of `cartopy` optional. That way it would be only used when it is installed, and eTraGo would also work without installing it. 
What do you think?

**Comment by fwitte** [comment]
Making it optional is a good idea! I'll make some adjustments to #434 (remove from setup.py and adjusting the imports in plot.py).
