### ISSUE TITLE
network.generators.e_nom_max values become NaN after ehv_clustering()

### ISSUE THREAD

**Issue by pieterhexen** [openego/eTraGo#427]
Before ehv_clustering():
<img width="236" alt="gen_before_clustering" src="https://user-images.githubusercontent.com/78430450/168967232-5129f396-1fba-4361-b739-006c206d7250.png">

After ehv_clustering():
<img width="228" alt="gen_after_clustering" src="https://user-images.githubusercontent.com/78430450/168967239-74f06358-6d61-4cae-88f1-efb0e58dd387.png">

**Comment by CarlosEpia** [comment]
@pieterhexen do you know if this column was recently added to network.generators? I don't see it in previous BKs. In the case of "yes", do you know the objective of it? I will create a short PR to solve this problem (just include "e_nom_max": np.min in strategies_generators() )

**Comment by pieterhexen** [comment]
@CarlosEpia I think this was added recently. @AmeliaNadal knows more about it. Can you add custom strategy np.max, please? Thanks :)

**Comment by AmeliaNadal** [comment]
e_nom_max was recently add to network.generators in https://github.com/openego/eGon-data/commit/0b3b6ca294ddc9359c22743ddd324f82188a8017
This value (in MWh(/y), default value = inf) could be used to set a constraint for the production over the year.

**Comment by CarlosEpia** [comment]
@pieterhexen I tested using np.sum() and the problem you described came up. Using np.max() the output is as expected, but I think there is another solution that could work better. What do you think if we implement and pass to the aggregation strategies a simple function that returns "np.inf" if there is an "inf" in the data, and returns np.sum in any other case?

**Comment by pieterhexen** [comment]
@CarlosEpia great idea! 
I am not sure whether it will work though because I think the problem is not related to "inf" but the grouping of multiple rows and their subsequent aggregation. Will you set up a little test for that or should I do it?

**Comment by CarlosEpia** [comment]
I could do it next Monday, but if you could run a test today, it would be also good for me.
