### ISSUE TITLE
scaling of line loading plot

### ISSUE THREAD

**Issue by lukasol** [openego/eTraGo#43]
In my opinion it always leads to confusion when the bar indicating the line loading is scaled differently. 
What do you think of just strictly scaling it to 0% - 100%? 

Obviously, the plots would often not be that nice and colorful, but that is also a message...

![gurobi_sh_21_ll](https://user-images.githubusercontent.com/17782967/30206080-414e1156-948b-11e7-99e9-9eae6175d5b6.png)

![gurobi_sh_20_ll](https://user-images.githubusercontent.com/17782967/30206115-56fd3f86-948b-11e7-8ce3-a092cdf3afe9.png)

**Comment by ulfmueller** [comment]
I would like to have it as an optional argument in the plotting function.

**Comment by MarlonSchlemminger** [comment]
Added 2 new attributes to plot_line_loading in branch features/plot-line-loading.
"Fixed_colors" makes the colorbar go from 0 to 100%, independent from the data. "boundaries" takes 2 values [startvalue, endvalue] and makes the colorbar go from startvalue to endvalue (see figure below). If fixed_colors is True, it overwrites the boundaries.
![pll_boundaries](https://user-images.githubusercontent.com/22960010/30925599-b24335c2-a3b2-11e7-8ff8-334383d6d6c7.png)

**Comment by lukasol** [comment]
Nice, that sounds good! And thank you for taking this over :)
@MarlonSchlemminger could you create a pull request if you think this is ready to merge?

**Comment by ulfmueller** [comment]
I just tried it out. It works fine. Cool! 

I have one idea for a minor adjustment. I think the combination of fixed_colors and boundaries is a bit confusing (e.g. to have a fixed boundary you need to state fixed_colors is false and then set your boundary...) 
I would suggest that you get rid of the attribute fixed colors and just stay with the boundaries. 
boundaries=[ ] -> no fixing, the legend is adjusted with respect to the min and max values of the data
boundaries=[some value, some other value] -> fixing to the desired values
boundaries=[0,100] -> would be the same thing which does the fixed_colors=True

Then either boundaries=[ ]  or boundaries=[0,100] could be the default value. I dont really care...

I think this is a bit more straight forward. What do you think? @MarlonSchlemminger could you change it like I suggested?

**Comment by MarlonSchlemminger** [comment]
Yeah sure, thats easy to do.

**Comment by MarlonSchlemminger** [comment]
I discovered another bug when startvalue is not 0 this morning, so I will push a new version when I fixed this as well.

**Comment by MarlonSchlemminger** [comment]
Removed fixed_colors and fixed the bug. @lukasol There is another new attribute in the function which is not ready to merge yet, I will talk to Ulf and merge as soon as this is ready as well.
