### ISSUE TITLE
Update bus weight loading from csv files in kmean-clustering

### ISSUE THREAD

**Issue by pieterhexen** [openego/eTraGo#442]
https://github.com/openego/eTraGo/blob/9abeb9bed0f336b0c81bcef4e7cca499fbc93771/etrago/cluster/networkclustering.py#L929
Does not work anymore -> Deprecated: https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.DataFrame.from_csv.html

For interest: We also had to update it in gasclustering.py https://github.com/openego/eTraGo/pull/441/commits/ed40d087da2d1164d2474167fb59c877469b063e

**Comment by CarlosEpia** [comment]
I will take care of this.
