### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eTraGo#445]
When developing the current version of eTraGo, we followed the code style rules of `pep8`. 
Right now, it sometimes happens that the code was formatted with `black`, I think that happened because we use it in eGon-data and are used to it. 
I would like to make a decision on the code style we want to use from now on to avoid conflicts. 

I had a look at the difference between the two options: `black` seems to be more strict but also follows `pep8` rules. `pep8` sometimes allows different code style options, `black` always selects the same one. 

For me, both options would be fine. I think it will be the choice between changing less things or be more consistent to our other tools. 

@CarlosEpia @AmeliaNadal @pieterhexen @fwitte: What do you think?

**Comment by pieterhexen** [comment]
After a quick look i didn't find an as easy to use auto-formating tool like black for pep8. Given that I like the formatting and it is very easy to use I am in favor of black. If we make a design-choice we should also open an issue and adapt all .py files in one go.

**Comment by CarlosEpia** [comment]
I think that using `black` could be a good option.

**Comment by fwitte** [comment]
I am in favour of `black` as well!
