### ISSUE TITLE
fix appl.py args documentation

### ISSUE THREAD

**Issue by pieterhexen** [openego/eTraGo#455]
There looks to be some merging residues and documenation is given in two different ways for "network_clustering".
https://github.com/openego/eTraGo/blob/5d6da7ba8c76ca1678833557729cd338f65a8627/etrago/appl.py#L327-L372

**Comment by CarlosEpia** [comment]
Thanks for reporting. I will take care of this.

**Comment by CarlosEpia** [comment]
Solved in 2ee14adcdd2081a9a5a8b548337d69b1aa874661.
