### ISSUE TITLE
Creation of adjacency_matrix() fails due to negative (-1) row/col index (eGon2035)

### ISSUE THREAD

**Issue by pieterhexen** [openego/eTraGo#474]

**Comment by pieterhexen** [comment]
Source of problem is Transformer '27697' that refers to a non-exitent bus1  '35206' 

@AmeliaNadal, @ClaraBuettner can you investigate this?

**Comment by ClaraBuettner** [comment]
> Source of problem is Transformer '27697' that refers to a non-exitent bus1 '35206' in scn eGon2035
> 
> @AmeliaNadal, @ClaraBuettner can you help?

Sorry for my late reply. This problem is already fixed in eGon-data. As soon as we have a new useful data model this problem will be solved.
