### ISSUE TITLE
Change of aggregation strategies

### ISSUE THREAD

**Issue by pieterhexen** [openego/eTraGo#477]
1. Would it make sense to switch the aggregation strategy for generators from https://github.com/openego/eTraGo/blob/17453105ce978edfa5e93e07608886c5dfdfaeeb/etrago/cluster/networkclustering.py#L287
to `np.sum` respectively apply the same logic as in https://github.com/openego/eTraGo/blob/17453105ce978edfa5e93e07608886c5dfdfaeeb/etrago/cluster/networkclustering.py#L278-L282?

2. Would it make sense to switch the aggregation strategy for links from https://github.com/openego/eTraGo/blob/17453105ce978edfa5e93e07608886c5dfdfaeeb/etrago/cluster/networkclustering.py#L306
to `np.sum` in order to not loose the information about the full length of all aggregated links?

**Comment by pieterhexen** [comment]
What do you think @AmeliaNadal, @CarlosEpia, @ClaraBuettner and @fwitte?

**Comment by CarlosEpia** [comment]
Hi Pieter,
I totally agree about the first point. Regarding the second one, I would prefer to keep the strategy as it is now. I think that np.sum could lead to overestimations.

**Comment by pieterhexen** [comment]
Thanks for your feedback @CarlosEpia ! I think so too and will update accordingly.
