### ISSUE TITLE
Change "solver_options" in args

### ISSUE THREAD

**Issue by CarlosEpia** [openego/eTraGo#496]
Make in args  "solver_options": {
        'BarConvTol': 1.e-5,
        'FeasibilityTol': 1.e-5,
        'method':2,
        'crossover':0,
        'logFile': 'solver_etragos.log'
        },

**Comment by ClaraBuettner** [comment]
Could you please also add threads: 4 ? Thank you!

**Comment by CarlosEpia** [comment]
Sure. It will be:
"solver_options": {
'BarConvTol': 1.e-5,
'FeasibilityTol': 1.e-5,
'method':2,
'crossover':0,
'logFile': 'solver_etragos.log',
'threads': 4
},
