### ISSUE TITLE
p_max_pu too high after using ehv clustering

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#5]
After this [commit](https://github.com/openego/eTraGo/commit/dde3ae8948b50f98f22f69bd950ee24103e4abb7) the problem is still pending.
I know @s3pp is already working on it. Just to have this pending task transparent here. Discussion might help as well...

**Comment by s3pp** [comment]
Unfortunately we could not see this in the IIS : (. Stacked generation plot looks much better now.

**Comment by ulfmueller** [comment]
the corresponding feature branch in the PyPSA fork was also merged into the dev. Therefore I changed the [requirements](https://github.com/openego/eTraGo/commit/f1fd6c9402333252509a2ec7e3a157727cb15b91) @s3pp @wolfbunke @IlkaCu @lukasol Please update your settings...
