### ISSUE TITLE
Extendable storages and infeasible lopf

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#50]
We have talked about it already, I think.
Load shedding makes the lopf for the 'Status Quo' scenario feasible. Turning load shedding off and instead setting storage extendable on the other hand does not lead to a feasible result. To me, that makes no sense. Any ideas for reasons or solutions?

for reproducibility, take e.g. the following setting:
'gridversion':'v0.2.11', snapshot: 2320, 'scn_name': 'Status Quo'

**Comment by lukasol** [comment]
Thanks for bringing that up again.

To me, however, there is an explanation for this: 
in contrast to load shedding, the extendable storages need to get some filling, i.e. excess energy, before they can be used and set up. Thus, if you choose a few snapshots with a high load and low feed-in, the storages cannot be filled and are consequently not built. I tried a few other snapshots and also some longer periods and received feasible results.

Do you think that could be the reason?

**Comment by ulfmueller** [comment]
sounds very reasonable! thx!
