### ISSUE TITLE
Create plot to visualize power2hydrogen expansion

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eTraGo#507]
We would like to be able to plot the spatial distribution of the expanded capacity of power_to_H2 plants. 

This can be done based on the existing plot function plot_grid:
https://github.com/openego/eTraGo/blob/4517568e808a2db4361e9e16f62e96cbb86188be/etrago/tools/plot.py#L1439-L1659

The function includes options to visualize e.g. grid and storage expansion by different sizes and colors of buses and lines in the network. Before starting with implementing new options, I would have a look at the current function and try to understand what the different lines of code are doing. 

Here is one example for plotting grid and storage expansion: 
![storage_and_grid_expansion](https://user-images.githubusercontent.com/22964326/199955796-21ac2ebb-7a27-4f36-8915-061f8c713059.png)

To test plot functions and create new ones, you don't have to run the optimization. You can use pre-defined data on results which I will give to you.

**Comment by Alonsoju95** [comment]
Hi @ClaraBuettner I have just pushed the changes that plot power_to_H2. Now its plotting some results. Please check it when you have time and we can talk next week. 

I am going to check if the results that are shown have the correct data, etc...
Thanks
