### ISSUE TITLE
Remove line added in clustering preprocessing in 03ea74b

### ISSUE THREAD

**Issue by pieterhexen** [openego/eTraGo#509]
...when new ci_dump without respective nodes is in place. 

https://github.com/openego/eTraGo/commit/03ea74bf9b95a79bd013f225aa4275d55a9ca8b8

**Comment by ClaraBuettner** [comment]
Hi Pieter, I'm wondering if this is already necessary when we use the data model from 14th of November. One of the bus_ids doesn't exist anymore, the other one is in the south-east of Germany, which sees to be a different bus than before. What do you think?

**Comment by pieterhexen** [comment]
> Hi Pieter, I'm wondering if this is already necessary when we use the data model from 14th of November. One of the bus_ids doesn't exist anymore, the other one is in the south-east of Germany, which sees to be a different bus than before. What do you think?

Hey Clara,
thanks for mentioning :)
Unfortunately it is still necessary with the new dataset but the bus_ids changed. I updated the code lines in the current dev branch a few days ago. See https://github.com/openego/eTraGo/commit/5fbe5a01e927463b76a0996038dd83693b6d37b8
