### ISSUE TITLE
Does the 'line-grouped model' perform better?

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#51]
For the lopf, does the grouping of lines changes runtime? Can you do some comparison?

see #17

**Comment by mariusves** [comment]
The line grouping does indeed change the runtime of the calculations. I've done 3 runs with 2 calculations each (non grouped & grouped). The "Import section" included the line grouping process: 

First run:
Non grouped:
--> Import: 0.695 min
--> Calculations: 39.955 min

Grouped:
--> Import: 3.954 min
--> Calculations: 31.911 min

--------------------------------
Second run:
Non grouped:
--> Import: 0.686 min
--> Calculations: 42.436 min

Grouped:
--> Import: 4.336 min
--> Calculations: 37.944 min

--------------------------------
Third run:
Non grouped:
--> Import: 0.566 min
--> Calculations: 32.261 min

Grouped:
--> Import: 2.942 min
--> Calculations: 25.872 min

Even though the calculations are fairly quicker, the grouping of the lines seems to eat up the time gained. Summed up the difference seems to be fairly small...

**Comment by ulfmueller** [comment]
Could you do some testing with more than 2 snapshots? May be with the sh scenario (faster)
I would expect that the calculation time will then outrun the extra time at the beginning?!

**Comment by mariusves** [comment]
Each calculation was done with 20 snapshots. I can try the SH scenario with 500 snapshots tomorrow.

**Comment by mariusves** [comment]
Here are the times for the SH Status Quo scenario with 1000 snapshots (2420-3420):

Non grouped:
--> Import: 0.092
--> Calculations: 24.004

Grouped:
--> Import: 0.118
--> Calculations: 17.601

**Comment by mariusves** [comment]
Got one more, this time with SH Status Quo and 3000 snapshots (crashed twice, because I ran out of RAM):

Non grouped:
--> Import: 0.199
--> Calculations: 123.333

Grouped:
--> Import: 0.227
--> Calculations: 79.46
