### ISSUE TITLE
Adapt export of busmaps while spatial clustering

### ISSUE THREAD

**Issue by KathiEsterl** [openego/eTraGo#564]
Several busmaps are exported during the spatial clustering. In specific settings, some files are overwritten. Additionally, the names are not clear.

**Comment by CarlosEpia** [comment]
Hi @KathiEsterl. Should we close this issue, or is there something still ongoing?

**Comment by KathiEsterl** [comment]
Oh right, I forgot to close this issue. 

@pieterhexen has a link to the branch to adapt the export of the gas busmaps accordingly, maybe we should have a new issue on that task? 

But I guess we can close this one.

**Comment by CarlosEpia** [comment]
We can change the name of this issue to something more general or create a new one. Both are ok for me.
