### ISSUE TITLE
load shedding

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#57]
@mariusves The adjustment of the load shedding function does not seem to work fine.
I think [this](https://github.com/openego/eTraGo/commit/6f67ba55540a1cd9e80598dfa836e80cbf80b73a) should fix the problem. Partly it does (now the id seems to be unique) but apparently it still does not work fine. 
Can you please check this out?

**Comment by mariusves** [comment]
The fix you committed should fix the "not-unique" bug. What other error are you getting while using this?

**Comment by ulfmueller** [comment]
@lukasol it looks like with your 3543fcd1549d9f14657d01c03b69cb74c7ec794a you accidentally got rif of my fix 6f67ba55540a1cd9e80598dfa836e80cbf80b73a Accident or purpose?

**Comment by lukasol** [comment]
definitely accidentally ;-) I tried to re-do that, but it didn't work out obviously...which one is the correct version?

**Comment by mariusves** [comment]
Correct version should be `start = network.generators.index.astype(int).max()`
Shall I fix it?

**Comment by lukasol** [comment]
Thx that would be nice!

**Comment by mariusves** [comment]
re-added the fix with 8c05628.

**Comment by ulfmueller** [comment]
> The fix you committed should fix the "not-unique" bug. What other error are you getting while using this?

I still get the error:
ERROR:pypsa.io:Error, new components for Generator are not unique
and in the following the problem is infeasible.

I just checked and calculated one problem with load sheding and one without. Both times the same amount of generators are connected. It seems your solutions is not working yet. Please fix this asap.

**Comment by mariusves** [comment]
fixed with a41958d. I had missed the `+1` at `start = network.generators.index.astype(int).max()+1`

I tested it and did not receiver the "not unique" error anymore.

**Comment by ulfmueller** [comment]
works for me know too. thx for dealing with this right away.

**Comment by ulfmueller** [comment]
nice now I can close this :+1:
