### ISSUE TITLE
Clustering doesn't work with load_shedding

### ISSUE THREAD

**Issue by KathiEsterl** [openego/eTraGo#581]
Right now, we run into a problem when having a network with load shedding and conducting the clustering. I guess, 'load_shedding' as a carrier needs to be added within the function calculating the weighting for the clustering. Probably the availability factor should be 0 to not consider load shedding in the weighting?
@CarlosEpia , could you have a look, please?

**Comment by CarlosEpia** [comment]
Hi Kathi. About this problem, we are currently using load shedding in a different way. We keep "load_shedding": False in the parameters and use the function after the clustering. It looks like this: 
![image](https://user-images.githubusercontent.com/62600091/214012286-1cc798ad-9b99-49b6-bf7b-738a61d8277c.png)

**Comment by KathiEsterl** [comment]
Yeah, that's right. Anyways, at some point we should fix this, right? I guess, in the end we want to have the opportunity to adapt this setting in the args and probably also keep the function etrago.load_shedding() in adjust_network, don't we?

**Comment by CarlosEpia** [comment]
Sure. I will take care of this issue.

**Comment by KathiEsterl** [comment]
> Sure. I will take care of this issue.

Thank you! :)
