### ISSUE TITLE
Try out pypsa k-means clustering

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#6]
created this [branch](https://github.com/openego/eTraGo/tree/features/k-means-clustering/etrago) to work on this.

to cite Jonas Hoersch:
"Code is in pypsa/networkclustering.py. The code idea is to build a
series termed busmap that maps the old buses index to the new buses
index and then call get_clustering_from_busmap to generate the new
network."

**Comment by ulfmueller** [comment]
I created a [first quick-and-dirty working version](https://github.com/openego/eTraGo/blob/features/k-means-clustering/etrago/k_means_testing.py#L110-L135)

**Comment by ulfmueller** [comment]
the remaining work would be 

- [ ] implement the [todo](https://github.com/openego/eTraGo/blob/features/k-means-clustering/etrago/k_means_testing.py#L112-L115) so that the x of the lines which are newly defined as 380kV lines are adjusted
-[ ] convert it to a function and move it [here](https://github.com/openego/eTraGo/blob/features/k-means-clustering/etrago/cluster/networkclustering.py)

**Comment by ulfmueller** [comment]
... and then of course test it and find out how we want to use it.

- comparison to ehv clustering.
- find out how many clusters make sense. 
- find out about the influence on the solutions.
- a similar workflow like for the snapshot clustering should be developed...

**Comment by ulfmueller** [comment]
I solved the issue with the x adjustment [here](https://github.com/openego/eTraGo/blob/features/k-means-clustering/etrago/appl.py#L97) (see checkbox above).
the other todos are still pending... @wolfbunke or @mariusves

**Comment by ulfmueller** [comment]
After reading the [contribution](https://arxiv.org/pdf/1705.07617.pdf) more closely I added an additional todo to the checkboxes.

**Comment by wolfbunke** [comment]
A new Branch is created in order to have the new dev applications. see: https://github.com/openego/eTraGo/tree/features/k-means-clustering2/etrago

**Comment by wolfbunke** [comment]
* Dev Branch and old k-means-clustering branch are merge together in [features/k-means-clustering](https://github.com/openego/eTraGo/tree/features/k-means-clustering). 
* The branch  k-means-clustering2 is deleted
* K-mean clustering is working as before

**Comment by wolfbunke** [comment]
* weighting by load and gen is implemented to K-mean in  65dd81f 
* function needs to be moved to some import files like tools etc.
* @ulfmueller  could you please test it and give feedback in order to close this issue soon.

**Comment by ulfmueller** [comment]
sure I can test it. Have you tested it so far? Could you perform a little evaluation how the weighting works? How it performs compared to the 'all buses have equal weighting'? Do you want me to do that or just checking if it works without raising an error?

**Comment by ulfmueller** [comment]
> function needs to be moved to some import files like tools etc.

are you planning on doing so before the friday release?

**Comment by wolfbunke** [comment]
and yes, I like to do it tomorrow so far.

**Comment by ulfmueller** [comment]
I changed the calculation of x to a more generic one by 6ee4fc4367f0a516ae2cdccde2ef71bc85ec9e9f
That issue popped up - I did not have it on the check list. Anyhow like that it should work fine. 
So the last remaining work is 
- [ ] 'cleaning up' aka make a function and move it to utilities.py and
- [ ] compare and test the results

But just the first thing is necessary in order to include this in the etrago release :) So go ahead Wolf! Thx!

**Comment by wolfbunke** [comment]
merged branch k-mean-clustering into dev  in d8bea00

**Comment by ulfmueller** [comment]
nice, Wolf! I hope it works. Next time, a pull request with a review for s.o. would be even nicer. This way I hope you reviewed it yourself sufficiently ;)

**Comment by wolfbunke** [comment]
oh, sorry! Yes it works with the last fix ;-)  65f0c31

**Comment by wolfbunke** [comment]
Shortly a visual plot of the difference with weighting by load and generation and without (all = 1)

**with weighting by load and generation:**
![kmean_figure_1_weighting](https://user-images.githubusercontent.com/14540685/30201183-170c4a04-947a-11e7-83c9-e7ed44338247.png)

**without weighting by load and generation:**
![kmean_figure_1_without_weighting](https://user-images.githubusercontent.com/14540685/30201187-1b57d376-947a-11e7-9e15-d82a87193caa.png)

**Comment by lukasol** [comment]
- [ ] add functionality to save the resulting cluster for reproducibility
- [ ] test k-means results.

**Comment by wolfbunke** [comment]
After our Webco I was testing the kmean function on the dev branch and it is working well for me. But I saw that n networks was set to 100 so maybe this  was irritating? 
What do you think about placing the number of networks as argument in args? Does it still not works for you?@BartelsJ @lukasoldi @ulfmueller

**Comment by BartelsJ** [comment]
I also tried it for 20 cluster and it worked for me as well. Regarding number of cluster as argument, I would prefer to change the input type to integer and automatically set k_mean_clustering=True for int > 0 or something similar.

**Comment by ulfmueller** [comment]
I changed it, that you can state directly the k in the args. See 321cb242afce3247e8b1b1f22c674cab5c042b02
Havent tried it out yet. Does the solution work for you?

**Comment by ulfmueller** [comment]
sorry, it works for me. It was a problem with my pypsa installation. I tested the above stated solution. It works fine. I would leave it like this if you agree.

**Comment by lukasoldi** [comment]
The results function will be implemented in #62, the testing takes place within #48
