### ISSUE TITLE
read-the-docs: What's new in 0.9.0

### ISSUE THREAD

**Issue by KathiEsterl** [openego/eTraGo#620]
Please collect the new features in this list to fill this chapter: https://etrago.readthedocs.io/en/latest/whatsnew.html#

- eTraGo is now compatible with Python 3.8
- eTraGo can now import and optimize networks that include other energy sectors such as gas, heating and mobility
- Various flexibility options from different energy sectors can be considered in the optimization:
-- Weather dependent capacity of transmission lines
-- Demand side management
-- Flexible charging of electric vehicles
-- Heat and hydrogen stores
-- Power2Hydrogen, Hydrogen2Power
-- Methanation and Steam-Methane-Reduction
- eTraGo arguments can now be partially provided and updated.
- eTraGo can now import datamodels from databases without using the ego.io
- Existing clustering methods were adapted to be able to reduce the complexity of not electrical sectors.
- Improvement of the ehv clustering (much faster now)
- A new clustering method "kmedoids-dijkstra" was implemented. This method considers the electrical distance between the buses in the network. It is also available for the methane grid.
- It is possible to select if the foreign buses are considered or not during the clustering process.
- The number of CPUs used to perform the clustering can be provided by the user. 
- A function to analyse the clustering results is included.
- Some more options are available to conduct a reduction in temporal dimension: 
a) segmentation: clustering of adjacent hours to segments of variable length
b) clustering to typical periods extended to cluster on weeks and months
- A temporal disaggregation is available through a 2-level-approach including a dispatch optimization on the temporally fullcomplex model
(-> if necessary, this can be conducted in slices to limit RAM usage)
- New plotting functions to visualize the optimization results from all the included energy sectors were implemented
- ...

**Comment by CarlosEpia** [comment]
Hi everybody. Please check the already existing bullet points in this issue and add the features that you consider should be also mentioned.

**Comment by ClaraBuettner** [comment]
I updated the list above and also changed the order a bit. 
I was wondering what is meant by "A function to analyse the clustering results is included." Can someone help me?

**Comment by ClaraBuettner** [comment]
Somehow my last changes were gone, but I updated the list above again. 
I still don't understand the point "A function to analyse the clustering results is included.". And I'm not sure if we want to add further details like the option to limit RAM usage in the temporal disaggregation. 
I guess I still forgot some new changes (at least the spatial disaggregation should be on the list as soon as it is working and merged).

**Comment by KathiEsterl** [comment]
> Somehow my last changes were gone, but I updated the list above again. I still don't understand the point "A function to analyse the clustering results is included.". And I'm not sure if we want to add further details like the option to limit RAM usage in the temporal disaggregation. I guess I still forgot some new changes (at least the spatial disaggregation should be on the list as soon as it is working and merged).

I added some more explanations on the temporal disaggregation directly to the _Whats New_-Section on the documentation-branch: #634
