### ISSUE TITLE
Feature market_simulation: Follow-Up Interface 

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#653]
This [branch](https://github.com/openego/eTraGo/tree/features/market-simulation) introduces a first working version of a consecutive market and grid optimization. Right now the interface between the two works without any code. Here is the todo: check if everything works fine, in particular check if all relevant components (except e.g. infrastructure) is non-aggregated and therefore the interface works fine.

**Comment by ClaraBuettner** [comment]
The current interface works fine (see #713). In case we want to implement sth. else, we will open a new issue anyhow, so I will close this one.
