### ISSUE TITLE
market_model needs a country tag

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#655]
Apply buses_by_country() and geolocation_buses() also on the market model like somewhere [here](https://github.com/openego/eTraGo/blob/51240f1df63cc465a0d48746657c9a997faed265/etrago/execute/market_optimization.py#L141)

**Comment by ClaraBuettner** [comment]
It looks like this was already done in https://github.com/openego/eTraGo/commit/9ec46197a71fa625bb374cee42d56058bebc703b 
Are there any other open tasks in this issue or can we close it?

**Comment by CarlosEpia** [comment]
We can close this issue.
