### ISSUE TITLE
Networkclustering creates subnetworks

### ISSUE THREAD

**Issue by lukasol** [openego/eTraGo#66]
Do you also encounter subnetworks when using networkclustering? Currently, I am working with NEP 2035 data on version v0.2.11 and receive 7 subnetworks...

**Comment by BartelsJ** [comment]
Is this still an actual issue? @lukasoldi

**Comment by lukasoldi** [comment]
It should be resolved with some changes by @ClaraBuettner, but I'm not certain these changes made it to the current data / dp version?! 
@IlkaCu @ulfmueller

**Comment by IlkaCu** [comment]
I'm pretty sure that Clara's bugfixes on subnetworks were not applied for the v0.2.11 data set. 
But it should be possible to apply the postprocessing scripts on this data set to fix it. @ClaraBuettner: Any objections?

**Comment by ClaraBuettner** [comment]
Currently the subnetworks are only fixed in the latest model_draft. It is possible to adjust the script to fix v0.2.11. But I suggest this can cause errors because grid and model_draft schema share a busmap in the db. It should work local when you create a new busmap.

**Comment by ulfmueller** [comment]
in the newer gridversion this is no issue anymore.
