### ISSUE TITLE
Update pypsa version (to 0.25.2)

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#663]
In general it is good to be state-of-the-art again and in particular I want to use the optimize_with_rolling_horizon() functionality (see #664 )...

I think it will be crucial then to mainly switch from lopf() to optimize() since many functionalities are no longer developed for the lopf()...

**Comment by ClaraBuettner** [comment]
This will also require updating pandas and python (now >=3.9) 
We should also decide if we want to use the new model-building option which would require adding our extra functionalities in this syntax.

**Comment by ClaraBuettner** [comment]
There is already pypsa 0.25.2 that includes some bugfixes, so I would directly switch to that version

**Comment by ClaraBuettner** [comment]
Changes in the clustering of pypsa require that all lines and transformers have an `r != 0 ` assigned. For lines, this will be done in the data model. But so far, no transformer has an `r` value. We should decide if we can/want to fix this in the data model creation or within etrago.

**Comment by ClaraBuettner** [comment]
Check arguments:

- [ ] ehv clustering
- [ ] k means (gas and AC)
- [ ] k medoid-dijkstra (gas and AC)
- [ ] snapshot clustering
- [ ] segmentation
- [ ] temporal disaggregation
- [ ] spatial disaggregation

**Comment by ClaraBuettner** [comment]
The current version of the feature branch is working fine with the parameters that are already checked in the list above. 
You can use the branch for some tests when you take into account that the other setting (eg. ehv clustering) are not working or not checked yet.
