### ISSUE TITLE
Update/add/refactor Unit Commitment Constraints

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#665]
in particular for our market simulation check and adjust UC constraints.
One possible 'easy to access' source at [pypsa-eur](https://github.com/PyPSA/pypsa-eur/blob/master/data/unit_commitment.csv)
Another source at [flexABLE](https://github.com/INATECH-CIG/flexABLE/blob/master/input/2019/FPP_DE.csv) based on [Künzel](https://publikationen.bibliothek.kit.edu/1000100456/50006897)

I think it makes sense to wait for #663 and then use the optimize() function instead of lopf() in order to get the complete picture of all UC constraints.

**Comment by ulfmueller** [comment]
First running example is implemented [here](https://github.com/openego/eTraGo/blob/85e8a9383dd657aaaad402b76bf13b62217dc1d0/etrago/execute/market_optimization.py#L156). 
But many details remain to be done:

- [ ] integrate pypsa-eur data, addressing [this dirty line](https://github.com/openego/eTraGo/blob/85e8a9383dd657aaaad402b76bf13b62217dc1d0/etrago/execute/market_optimization.py#L178)
- [ ] inlcude OCGT (and in general links) into the unit commitment (see [here](https://github.com/openego/eTraGo/blob/85e8a9383dd657aaaad402b76bf13b62217dc1d0/etrago/execute/market_optimization.py#L186)
- [ ] address seasonal storage behavior considering the interface between pre market model and UC market model ([somewhere here](https://github.com/openego/eTraGo/blob/features/market-simulation/etrago/execute/market_optimization.py#L170-L172). How to do might be found in the master thesis by @KathiEsterl concerning snapshot clustering or NEP insights (or further literature research).

**Comment by ClaraBuettner** [comment]
>     * [ ]  address seasonal storage behavior considering the interface between pre market model and UC market model ([somewhere here](https://github.com/openego/eTraGo/blob/features/market-simulation/etrago/execute/market_optimization.py#L170-L172). How to do might be found in the master thesis by @KathiEsterl concerning snapshot clustering or NEP insights (or further literature research).

Do you already have a concept for this? I mean sth. like which storages should be affected by this and which data is exchanged? I could implement it (and also think about the questions I had, I just wanted to know if there is already sth. there)

**Comment by ClaraBuettner** [comment]
All the mentioned points are already included. There might be additional changes and updates in the future, but I will close this issue for now.
