### ISSUE TITLE
Release 0.9

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eTraGo#670]
Finally we want to release eTraGo including all changes we did in eGon. 
The following steps need to be done:

- [x] fix #660 
- [x] Upload data to zenodo and link to it in the documentation
- [ ] check if all settings are working
- [x] check if documentation is correct
- [ ] add release date to whats_new
- [x] replace version number

**Comment by ClaraBuettner** [comment]
@CarlosEpia: Can we add the example notebook from the workshop? The documentations still refers to a new example: 
https://github.com/openego/eTraGo/blob/3411bae14a6e68d39e75a5b200b658f279304059/doc/howToUse.rst?plain=1#L58

**Comment by CarlosEpia** [comment]
Sure, I will include it it.

**Comment by ClaraBuettner** [comment]
> Sure, I will include it it.

But it is not linked in the rst file mentioned above, is it?

**Comment by CarlosEpia** [comment]
> > Sure, I will include it it.
> 
> But it is not linked in the rst file mentioned above, is it?

Now it is linked. The link refers to the file that will be available in the master branch (not there yet, but when merging [features/release-0.9.0](https://github.com/openego/eTraGo/tree/features/release-0.9.0))
