### ISSUE TITLE
Release 0.4

### ISSUE THREAD

**Issue by lukasol** [openego/eTraGo#68]
Hi, 
as you might know, there will be an eTraGo Release 0.4 this week. In order to include all the latest development, please make sure to merge your work into dev and close the respective issue if finished. You can find all issues supposed to go into Release 0.4 by sorting the issues by their milestone. 

If you cannot finish a ticket assigned to this milestone by this Thursday, please state that here.

**Comment by s3pp** [comment]
#33 will not be resolved in time for release 0.4

**Comment by lukasol** [comment]
eTraGo version 0.4 has been successfully released.
