### ISSUE TITLE
Temporary file during clustering

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eTraGo#694]
@CarlosEpia When I run eTraGo, some files called "df.p" are created by this lines:

https://github.com/openego/eTraGo/blob/a98017f6e6df06db5f6def69de79627cd91310d1/etrago/cluster/spatial.py#L425

https://github.com/openego/eTraGo/blob/a98017f6e6df06db5f6def69de79627cd91310d1/etrago/cluster/spatial.py#L657

I don't know why these files are needed. Can you help me?

**Comment by CarlosEpia** [comment]
I can imagine those lines were included by Martin to debug in case of needed. These files are never imported, so I can delete those lines and run a couple of calculations to be sure that they are not needed any more. Does it sound good?

**Comment by ClaraBuettner** [comment]
Ah okay, I thought you would have added these lines. 
If you could try out what you wrote that would be great
