### ISSUE TITLE
Bug in requirements.txt

### ISSUE THREAD

**Issue by mariusves** [openego/eTraGo#70]
While trying to install eTraGo with the requirements [these lines ](https://github.com/openego/eTraGo/blob/dev/requirements.txt#L5-L6)caused an error.
I commited a [quick hotfix](https://github.com/openego/eTraGo/commit/f420b70beae3df6f32eb50ea0551d7db16d4d565), could you share some insights if the now commented-out lines are necessary?

**Comment by wolfbunke** [comment]
no, I removed them. Please just merge my pull request of #71. Thank you!

**Comment by mariusves** [comment]
Fixed, thanks for the quick response!
