### ISSUE TITLE
incompatible python version due to pypsa restriction

### ISSUE THREAD

**Issue by IsGut** [openego/eTraGo#718]
in your release for version 0.9.0 you mention: eTraGo is now compatible with Python 3.8
in your setup.py you specify restriction: "pypsa == 0.26.2"
in pypsa 0.26.2: python_requires=">=3.9"

**Comment by ClaraBuettner** [comment]
The dev-branch needs python3.10. That is unfortunately not part of the documentation so far as we often only update the documentation when releasing. I will see if I can already document this somewhere.
