### ISSUE TITLE
Dev failing when importing scenario data

### ISSUE THREAD

**Issue by CarlosEpia** [openego/eTraGo#728]
eTraGo is failing with the next error message:

File ~/env/etrago_pr_710/lib/python3.10/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
exec(code, globals, locals)

File ~/git/eTraGo/etrago/appl.py:770
etrago = run_etrago(args, json_path=None)

File ~/git/eTraGo/etrago/appl.py:678 in run_etrago
etrago.build_network_from_db()

File ~/git/eTraGo/etrago/tools/network.py:377 in build_network_from_db
self.scenario = NetworkScenario(

File ~/git/eTraGo/etrago/tools/io.py:129 in init
self.configure_timeindex()

File ~/git/eTraGo/etrago/tools/io.py:159 in configure_timeindex
tr = saio.as_pandas(

File ~/env/etrago_pr_710/lib/python3.10/site-packages/saio.py:181 in as_pandas
df = pd.read_sql_query(query.statement, query.session.bind,

File ~/env/etrago_pr_710/lib/python3.10/site-packages/pandas/io/sql.py:526 in read_sql_query
return pandas_sql.read_query(

File ~/env/etrago_pr_710/lib/python3.10/site-packages/pandas/io/sql.py:2739 in read_query
cursor = self.execute(sql, params)

File ~/env/etrago_pr_710/lib/python3.10/site-packages/pandas/io/sql.py:2671 in execute
raise TypeError("Query must be a string unless using sqlalchemy.")

TypeError: Query must be a string unless using sqlalchemy.

**Comment by CarlosEpia** [comment]
Update: The last package version that was modified was pypsa. Installing eTraGo using the previous version, the function build_network_from_db() works normally.

**Comment by ClaraBuettner** [comment]
I am quite sure that the error is not related to pypsa for several reasons: 
- we did many tests when updating tp the new pypsa version 
- I have environments with the newer pypsa version that do not run into this problem 
- the error occurs not in pypsa, it looks more like sqlalchemy or pandas

Was any other package downgraded when you downgraded pypsa?
