### ISSUE TITLE
Check out the plotly liberay use within network.iplot() of the new release of PyPSA

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#79]
The new PyPSA version 0.11.0 has a pretty cool plotting function...
https://pypsa.org/examples/scigrid-lopf-then-pf-plotly.html

Might be a reason to upgrade to the newest PyPSA version.

@lukasoldi @BartelsJ @wolfbunke @MarlonSchlemminger

**Comment by mariusves** [comment]
Those are some fancy looking plots!

I just hope the changes in the PyPSA API don't break too much code in eTraGo...

**Comment by ulfmueller** [comment]
@mariusves Could you check out /test how much we would have to change in order to upgrade?

**Comment by mariusves** [comment]
I'm on it!

**Comment by mariusves** [comment]
Just a quick feedback. There don't seem to be too many API changes. 
Unfortunately, gurobi crashes for me doing the usual LOPF. Currently checking out why that happens...

On another note, what about the changes we commited to the PyPSA ego-fork ? If we plan to upgrade PyPSA these changes might get lost, thus we could first try to bump our fork to the newest version.
I'm testing out the first basic features of eTraGo with PyPSA11 though, more on the details later.

**Comment by mariusves** [comment]
Kinda found the problem. Since PyPSA 0.9.0 when doing the LOPF, the solver lp file contains `nan`-values:
```
Solver log:
        Error reading LP format file C:\Users\Marius\AppData\Local\Temp\tmp_c2bj_e0.pyomo.lp at line 487746
        Unrecognized variable bound
        Neighboring tokens: " 0 <= x4249 <= nan 0 <= x4250 <= "
```

This had not been the case before. I'm now trying to find where those values come from (maybe from empty q_sets?)

**Comment by ulfmueller** [comment]
mmh, well the lopf does not take p_set and especially no q_set. So that should not be the problem...
is that the upper bound? maybe a problem with inf values.
Can you provide a lp file? Or save the lp file an search for nan values. Then you might locate the problem...

**Comment by mariusves** [comment]
the lp-file is fine until it reaches line 487746 where a lot of values become NaN:
```
   ...
   0 <= x4247 <= 30.716205170066882
   0 <= x4248 <= 24.374999107213071
   0 <= x4249 <= nan
   0 <= x4250 <= nan
   0 <= x4251 <= nan
   0 <= x4252 <= nan
   0 <= x4253 <= nan
   0 <= x4254 <= nan
   0 <= x4255 <= nan
   0 <= x4256 <= nan
   ...
```

I might have found the culprit. Using
`network.generators_t.p_max_pu[network.generators_t.p_max_pu == np.isnan(network.generators_t.p_max_pu)]`
shows that a lot of generators have NaN values for `p_max_pu`, some for all timesteps, some only for certain.

**Comment by ulfmueller** [comment]
maybe the generators which do not get p_max_pu as a series (wind and solar) but as a constant (former p_max_pu_fixed)?!

**Comment by mariusves** [comment]
Here is the lp-file with the `nan`-values (stating in line 63195,generator_p) :
[pypsa_11_error.txt](https://github.com/openego/eTraGo/files/1434631/pypsa_11_error.txt)

**Comment by ulfmueller** [comment]
Which scenario/version did you take as input?
definitely generators with the ids 23022, 23482 and so on. It happens with 543 generators. Could those be all the flexible power plants with static p_max_pu?
May be you still have some minutes to check some of these generators and which input data they are missing?!

**Comment by ulfmueller** [comment]
@ClaraBuettner Can you post your progress here? Since you found a crucial code line which has to be changed. I cannot see that you pushed your efforts in the corresponding [branch](https://github.com/openego/eTraGo/tree/feature/upgrade-to-pypsa-11). Could you please push the changes you applied?

**Comment by ClaraBuettner** [comment]
I will do that as soon as I can, right now I'm in the train and can't get online with my Laptop. And the mobile Version doesn't work very well...

**Comment by ClaraBuettner** [comment]
I just changed the version number in the branch, so the colunms can be renamed. 
But it still doesn't work for me. Since I've installed pypsa 0.11 the solver can not read the model, even if I downgrade to pypsa 0.8 again. 
Does anybody has the same problem? I noticed that pyomo and scipy update when I installed pypsa 0.11, may that cause a problem?

**Comment by ClaraBuettner** [comment]
I just calculated a lopf with pypsa 0.11. 
The problem was the upgrade from pandas 0.19.1 to 0.21, when I dowgraded pandas it worked fine.

**Comment by ulfmueller** [comment]
Now, we should figure out what the problem is with the new pandas and what code we would have to adapt.

**Comment by ClaraBuettner** [comment]
The requirements for pypsa0.11 inculde pandas>= 0.19.0, so I tested etrago functions with pypsa 0.11 and pandas 0.20.3 (which is the newest working version).
Functions line_grouping, parallelisation, load_shaeeding and k_means_clustring work fine. 
Network_clustrering seems to need the pypsa fork, I havn't updated for pypsa 0.11 yet, because I don't know how to do that.
When calculating with reproduced generator noise, calculations with pypsa 0.8 and 0.11 have the same results. I tested this by looking at the line_loading_plot and also created result-csv-files to check them randomly.

**Comment by ClaraBuettner** [comment]
I updated the fork and tried to test the network_clustering function. But it includes network.now which has been removed since pypsa 0.9.0. 
After replacing it with network.snapshots network_clustering works fine.

**Comment by wolfbunke** [comment]
iplot() as the newer versions of pypsa provides are not part of eTraGo any more. Based on eGo, ego.iplot based on Leaflet and folium plots eTraGo's results as an interactive html file. see: 
https://github.com/openego/eGo/blob/dev/ego/tools/plots.py#L362
