### ISSUE TITLE
develop line loading minimization within the extra_functionality of the lopf()

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#8]
goal:
- prevent optima plateau
- maybe approximate line loss effects?!

for more information see [here](https://groups.google.com/forum/#!topic/pypsa/jVhmvoBh8WE)

**Comment by ulfmueller** [comment]
now the objective function is added by an additional line-flow-reduction statement by an  [extra_functionality](https://github.com/openego/eTraGo/blob/features/line-loading-minimization/etrago/extra_high_voltage_SH_appl.py#L118-L123)

Principally this works. But like that, negative values of flows would be minimized and therefore maximized which does not make sense.
Therefore the remaining problem is that the branch flows have to be absolute values. This is kind of tricky since the problem then becomes non-linear. With gurobi a quadratic solution can work but it makes the process rather slow and unstable.
[here](https://math.stackexchange.com/questions/432003/converting-absolute-value-program-into-linear-program) you can find out more about the issue of wanting to convert the variable to absolute values. @IlkaCu  It could be worth trying out [this suggested solution](https://math.stackexchange.com/a/432029)

**Comment by ulfmueller** [comment]
By the way this approach is mainly (concerning 'optima plateau' or better called 'degeneracy') addressing the same problem as the solution developed in #4

**Comment by ulfmueller** [comment]
Kim, successfully implemented the function. I would now clean up a bit and push the development into the dev branch. 

First test have shown that computation time is essentially slowed down by this method (roughly factor 2). Therefore a new idea popped up. We could perform the line loading minimization once for all scenarios in order to define a marginal cost noise (see #4 ) which is 'inspired' by that minimal line loading result and which can reproduce that setting without increase of computation time.
One aspect to think about is that the line loading minimization could produce different settings from snapshot to snapshot. And we want only one marginal cost setting set once for all snapshots.
@kimvk @lukasol Maybe we can develop together how we proceed?

**Comment by lukasol** [comment]
Yes. let's develop that. 
What if we do a full-year run similar to the load shedding analyses carried out in #19 (with parallelization and without storage) for the line loading minimization and assign noises according to these results?

**Comment by lukasol** [comment]
@kimvk could you create a new ticket for that and close this one?
