### ISSUE TITLE
network.carriers (former source) table empty

### ISSUE THREAD

**Issue by mariusves** [openego/eTraGo#84]
I noticed that after the components the table network.carriers (former sources) is empty.
I know that the source table is being used to "translate" from the source_ids to the actual source name, but during the import process the "official" PyPSA table remains empty.

Could you maybe take a look where in the import function this takes place and how it could be implemented so the table is filled again?

**Comment by s3pp** [comment]
That's kind of messy, but could work, I will have a look at it again though.
