### ISSUE TITLE
Error DB import Multiple rows were found for one()

### ISSUE THREAD

**Issue by wolfbunke** [openego/eTraGo#85]
After updating eTraGo, egoio and pypsa fork I got following error:

```
Traceback (most recent call last):
  File "/home/dozeumbuw/eTraGo/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2756, in one
    ret = self.one_or_none()
  File "/home/dozeumbuw/eTraGo/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2735, in one_or_none
    "Multiple rows were found for one_or_none()")
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one_or_none()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "appl.py", line 309, in <module>
    network = etrago(args)
  File "appl.py", line 204, in etrago
    scn_name=args['scn_name'])
  File "/home/dozeumbuw/eTraGo/src/eTraGo/etrago/tools/io.py", line 103, in __init__
    self.configure_timeindex()
  File "/home/dozeumbuw/eTraGo/src/eTraGo/etrago/tools/io.py", line 121, in configure_timeindex
    ormclass.temp_id == self.temp_id).one()
  File "/home/dozeumbuw/eTraGo/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2759, in one
    "Multiple rows were found for one()")
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one()
(eTraGo) dozeumbuw@n00004755:~/eTraGo/src/eTraGo/etrago$ 

```

Any idea @mariusves ?

**Comment by ClaraBuettner** [comment]
Ulf found out that the problem is caused by multiple rows in the temp_resolution table. I added a filter on the version in  configure_timeindex in etrago.io and it worked. There is no entry for version v0.2.11 so I had to choose v0.2.10. Is it possible to add this? Then I could filter with the version numer which would be much better. 

` def configure_timeindex(self):
        """
        """
        global timeindex
        global tr
        
        try:

            ormclass = self._mapped['TempResolution']
            if self.version:
                tr = self.session.query(ormclass).filter(
                ormclass.temp_id == self.temp_id).filter(ormclass.version == 'v0.2.10').one()
                
            else:
                tr = self.session.query(ormclass).filter(
                ormclass.temp_id == self.temp_id).one()
       
        except (KeyError, NoResultFound):
            print('temp_id %s does not exist.' % self.temp_id)
       
            
        timeindex = pd.DatetimeIndex(start=tr.start_time,
                                     periods=tr.timesteps,
                                     freq=tr.resolution)

        self.timeindex = timeindex[self.start_snapshot - 1: self.end_snapshot]
`

**Comment by s3pp** [comment]
Very nice! I agree, using self.version would be much better.

**Comment by wolfbunke** [comment]
Thank you! Your filter works for most of the args settings. I add v0.2.11 to the grid.ego_pf_hv_temp_resolution table. Using self.version sounds great.

**Comment by s3pp** [comment]
Would you be so kind to implement this fix? @ClaraBuettner  I guess, you can do it right on the dev branch.

**Comment by ClaraBuettner** [comment]
I implemented it on the dev branch.

**Comment by s3pp** [comment]
Thanks!
