### ISSUE TITLE
Improve docstrings on io.py in eTraGo/tools/io.py

### ISSUE THREAD

**Issue by s3pp** [openego/eTraGo#89]
A lot of docstrings are not there.

**Comment by s3pp** [comment]
Related to #84

**Comment by wolfbunke** [comment]
Is the work done with your commit 182a84e ?

**Comment by wolfbunke** [comment]
@s3pp ?

**Comment by s3pp** [comment]
I don't know if it's done, but I do think that it is an improvement.
