### ISSUE TITLE
infeasibility hunting using load shedding

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#9]
Attaching load shedding generators by something like

```
network.add("Carrier", "load")
      network.import_components_from_dataframe(
          pd.DataFrame(
              dict(marginal_cost=1e4,
                   # intersect between macroeconomic and surveybased
                   # willingness to pay
                   # http://journal.frontiersin.org/article/10.3389/fenrg.2015.00055/full
                   p_nom=1e6,
                   carrier='load',
                   bus=network.buses.index),
              index=network.buses.index + ' load'),
          "Generator"
      )
```

and then looking at where and when there is load shedding in order to hunt infeasibility locations

- [x] test it
- [x] write a little load shedding function

I will work on this [branch](https://github.com/openego/eTraGo/tree/features/load-shedding)

**Comment by s3pp** [comment]
As mentioned this could be implemented by adding functionality to PyPSA's network_lopf function or creating a utility function in eTraGo. 

1. network_lopf function is parsed to pypsa.Network on instantiating. It is located in PyPSA/pypsa/opf.py and could be refactored to include load-shedding functionality. Adding an additional parameter in the function call is one possibility. Implementation would be done in the openego/PyPSA fork, creating a new features branch. Benefit of code contribution to PyPSA.

2.  Adding a new add_load_shedding function in eTrago/extras/utilities.py. The function call would most likely include default parameters.

**Comment by ulfmueller** [comment]
1. is implemented [here](https://github.com/openego/PyPSA/commit/d5ab623deee1a91494f39f9b1aac4b9d9b5ffa2e)

2. is implemented [also](https://github.com/openego/eTraGo/commit/1ca7f928d9b0e17e9f6d5b0cdbde92d39d35270d)

both ways work fine. It could be the question if 1. could be a pull request for the FIAS guys. Also it seems that the seperate function is the better way since the network_lopf() function might not be the adequate place to change the network model since it is the function to solve the model...
Any opinions?

2. I will merge to the network clustering branch. Eventually it would be nice to merge it to the dev branch...

**Comment by lukasol** [comment]
I think the separate option sounds cleaner. 
Is it true that there should not be any infeasible solutions when using load_shedding? Because I just experienced the opposite when applying the second option...or is there anything that I need to do apart from running the function?

**Comment by ulfmueller** [comment]
I think so too. it is a clearer cut between network building and solving the problem. But the second one is somewhat cool too...
you have to run the function before executing the lopf(). nothing else you should have to do. 
The only reason for still having infeasibilities would be if there is something wrong with the lines or transformer e.g. x values which have null values... but if you run the calculation on the same scenario and dataset this could not be the reason...
Cannot imagine right now what the problem is :(

**Comment by lukasol** [comment]
I think the problem mentioned above is resolved since it works for me now. However, my impression is that the load shedder is used quite often, i.e. for a week in the SH test scenario. At the same time, no extendable storages are set. What if we increase the price for the load shedder in order to avoid too much competition with the storages?

**Comment by ulfmueller** [comment]
yes. I have thought about that issue as well. We can do that of course. But anyway, in my mind if we optimize with storage investment options I would simulate without load shedding. Then the storages do that job and we do not have the mentioned conflict. Don't you think? Do I miss s.th.?

**Comment by lukasol** [comment]
No, that's true. 
Computation time does however increase clearly when using storage instead of load_shedding.

Since the load shedder is implemented, tested and working now, I propose to close this issue.
