### ISSUE TITLE
Versioning of eTraGo results in oedb

### ISSUE THREAD

**Issue by ulfmueller** [openego/eTraGo#95]
Right now we can store results in the model_draft. But once a new dp run is released the entire data will be lost. Therefore it would be good to find a solution for saving results also to a versioned schema 'grid' or 'scenario'.

2 possible options (in my mind):
- the meta table of the model_draft gets an additional argument, which states which datasets should be safed. Due to this column a script which can be included at the beginning of the dp copies them into the versioned schema
- one can directly save results not only into model_draft but also to a versioned schema.

@mariusves what do you think?

**Comment by mariusves** [comment]
I think both options can be added, whereas the first can be implemented quite quickly. I'd propose to implement this check and the copy function to this file dataprocessing/sql_snippets/ego_dp_powerflow_hv_setup.sql .

For the second option, I will have to adjust the export function a tiny bit, nothing major though. Since I need to duplicate the table definitions for the first option in ego.io anyways, I can reuse them for this purpose as well (telling the export function the destination, so to say).

**Comment by ulfmueller** [comment]
But if we do both options, we can get a result_id problem if we would add result data sets from two sides, right?

**Comment by ulfmueller** [comment]
maybe we just stick with the first solution. The place in the dp you suggest I think is good! 
p.s.: welcome back!

**Comment by IlkaCu** [comment]
I would propose to save scripts for adding the result data to our versioned schemas separated from the DP scripts, because the result data are no direct outcome of the DP but the powerflow calculations. We could for example save it in the utilities folder and run it every time its needed.

**Comment by ulfmueller** [comment]
sounds good. And the setup of the results tables which happens [in this dp branch](https://github.com/openego/data_processing/blob/features/add-pf-result2db/dataprocessing/sql_snippets/ego_dp_powerflow_hv_setup.sql#L1152-L1154) would move to the preprocessing or also to the utilities! Otherwise the tables would be deleted when a new dp run is executed.

**Comment by ulfmueller** [comment]
And we have to clarify in which versioned schema should the results go! I guess 'scenario' or 'grid'. The definition (here)[https://wiki.openmod-initiative.org/wiki/Database_schema] is not clear on that. @Ludee @MGlauer @IlkaCu In which schema would you put modelling results in the oedb?

**Comment by MGlauer** [comment]
For starters you might consider putting it in the model_draft. This schema is for datasets that are still under development and thus not fit for the slow-paced versioning protocol. Are your results in a state where you can call them consolidated?

**Comment by ulfmueller** [comment]
we have them already in the model_draft. Now we want to establish a workflow to be able to store them also stably and permanently in a versioned schema (e.g. for referencing in a paper). The question is: which schema should we choose?

**Comment by Ludee** [comment]
Since all data is "modelling results" (except raw measurement data), the suitable schema would definitely be **grid**. 
Can you adapt the eGoDP versioning methods with a versioning table that got appended!?

The **scenario** schema is indeed not defined precisely. We will work on that ;)

**Comment by ulfmueller** [comment]
Thx for the feedback. 
@mariusves We take grid then :smile: 
@IlkaCu said (and I can agree to that) that the versioning of results which come from an application like 'eTraGo' are not really part of the data processing. Therefore we would put this into the utilities folder. This would have the advantage that we do not depend on an entire dp run since we would execute it when needed....
Any doubts or objections?

We could even think about putting it into eTraGo itself. And then it would be more sustainable to write it directly in sqlalchemy...

**Comment by IlkaCu** [comment]
During our last conference call we decided to put the versioning scripts into the eTraGo repository. The scripts which create the results tables stay in the dataprocessing. 
Additionally we favour to use sqlalchemy for the versioning.

**Comment by ulfmueller** [comment]
This was done withing the [latest release](https://github.com/openego/eTraGo/tree/0.5.1)
