### ISSUE TITLE
missing branches in grid model

### ISSUE THREAD

**Issue by nesnoj** [openego/eTraGo#96]
Not sure if this is the right repo, but:
I found some 110kV-lines which obviously exist but are not included in the table `grid.otg_ehvhv_branch_data` near "UW Jessen Nord" (bus_i = 28061 in table `grid.otg_ehvhv_bus_data`). They should be connected to branch 21026..

![osmtgmod_bug1](https://user-images.githubusercontent.com/15910173/32890426-00500068-cacf-11e7-92a7-733d24473963.png)

This might be interesting for you..

**Comment by nesnoj** [comment]
Oh, this EHV/HV substation was [installed in 2016](http://www.50hertz.com/de/Netzausbau/Leitungen-an-Land/Netzanschluss-Jessen-Nord/Meldungen), probably it wasn't included in the OSM data used by osmTGmod?!

**Comment by lukasoldi** [comment]
Probably. our osm data is still dated 2016-10-01...

**Comment by nesnoj** [comment]
Ok.
Is an OSM update already scheduled? @Ludee

**Comment by Ludee** [comment]
Planed but not scheduled!
How important/ urgent is it?

I can help organising but @gnn will have to execute it in Magdeburg.

**Comment by nesnoj** [comment]
It is not very urgent but it'd be great to have recent data by the end of this year..

**Comment by nesnoj** [comment]
ok, I close this one and get back to you later..

**Comment by nesnoj** [comment]
I need a current HV dataset asap. Anything new about the OSM update?

If not, I'd fix it manually for my specific application since a manual update of all related/derived eGo-tables were (at least for me) not fail-safe at all..
Related: #97

**Comment by IlkaCu** [comment]
During our last project meeting we decided to stay with the current OSM data set until we finish the project. Would that be okay for you? 
@ClaraBuettner already described and fixed some other topology errors for the EHV level in this [issue](https://github.com/openego/osmTGmod/issues/10). Would it be possible to include a similar 'manual' bug fix in the DP for your case?

**Comment by nesnoj** [comment]
Thanks for getting back to me. A manual bugfix would suit my needs..

I fixed this 110 KV issue manually by adding these new lines without touching the original DP tables (as mentioned above, I do not want to break your model). I'm ok since it works for me.. Bit if it is crucial for eGo, @ClaraBuettner may fix it in the eGo tables..?!

**My solution**
Notes:
- I fixed it in derived bus and line tables, not the osmTGmod ones
- my table names hold the prefix "wn_"
- line geoms are straight lines (geom and topo column)
- I used the OSM node id as bus id for the 2 new buses
- electrical properties were calculated manually using existing data for 110kV (avg for this type)
```
-- 1a) Insert 2 missing buses on 110kV line
INSERT INTO model_draft.wn_abw_ego_pf_hv_bus
    (version, bus_id, v_nom, geom, hvmv_subst_id, in_region)
  VALUES
    ('v0.3.0', 1851699628, 110, ST_SetSRID(ST_Point(13.0317764, 51.7792147), 4326), 2482, True),
    ('v0.3.0', 1851699629, 110, ST_SetSRID(ST_Point(13.0289850, 51.7797518), 4326), 2482, True)
;

-- 1b) Lines from substation (Jessen Nord) buses to buses
INSERT INTO model_draft.wn_abw_ego_pf_hv_line
    (version, line_id, bus0, bus1, x, r, g, b, s_nom, length, cables, frequency, geom, topo)
  VALUES
    ('v0.3.0', 461202177, 28063, 1851699628, 0.6138, 0.17754, 0, 0.000019455, 520, 3.3, 6, 50, 
      (SELECT ST_SetSRID(ST_Multi(ST_MakeLine(bus.geom)), 4326)
         FROM model_draft.wn_abw_ego_pf_hv_bus AS bus
         WHERE bus.bus_id in (1851699628, 28063)),
      (SELECT ST_SetSRID(ST_MakeLine(bus.geom), 4326)
         FROM model_draft.wn_abw_ego_pf_hv_bus AS bus
         WHERE bus.bus_id in (1851699628, 28063))
    ),
    ('v0.3.0', 461202186, 28063, 1851699629, 0.6138, 0.17754, 0, 0.000019455, 520, 3.3, 6, 50, 
      (SELECT ST_SetSRID(ST_Multi(ST_MakeLine(bus.geom)), 4326)
         FROM model_draft.wn_abw_ego_pf_hv_bus AS bus
         WHERE bus.bus_id in (1851699629, 28063)),
      (SELECT ST_SetSRID(ST_MakeLine(bus.geom), 4326)
         FROM model_draft.wn_abw_ego_pf_hv_bus AS bus
         WHERE bus.bus_id in (1851699629, 28063))
    )
;

-- 1c) Split and reconfigure existing 110kV line
UPDATE model_draft.wn_abw_ego_pf_hv_line
  SET
    bus1 = 1851699628,
    length = 15.9,
    x = 6,
    r = 1.735,
    b = 0.0000475,
    geom = (SELECT ST_SetSRID(ST_Multi(ST_MakeLine(bus.geom)), 4326)
              FROM model_draft.wn_abw_ego_pf_hv_bus AS bus
              WHERE bus.bus_id in (20759, 1851699628)),
    topo = (SELECT ST_SetSRID(ST_MakeLine(bus.geom), 4326)
              FROM model_draft.wn_abw_ego_pf_hv_bus AS bus
              WHERE bus.bus_id in (20759, 1851699628))
  WHERE line_id = 21026
;

INSERT INTO model_draft.wn_abw_ego_pf_hv_line
    (version, line_id, bus0, bus1, x, r, g, b, s_nom, length, cables, frequency, geom, topo)
  VALUES
    ('v0.3.0', 99999999990, 1851699628, 1851699629, 0.0755, 0.0218, 0, 0.000000597, 260, 0.2, 3, 50, 
      (SELECT ST_SetSRID(ST_Multi(ST_MakeLine(bus.geom)), 4326)
         FROM model_draft.wn_abw_ego_pf_hv_bus AS bus
         WHERE bus.bus_id in (1851699628, 1851699629)),
      (SELECT ST_SetSRID(ST_MakeLine(bus.geom), 4326)
         FROM model_draft.wn_abw_ego_pf_hv_bus AS bus
         WHERE bus.bus_id in (1851699628, 1851699629))
    ),
    ('v0.3.0', 99999999991, 1851699629, 25600, 1.547, 0.447, 0, 0.000012249, 260, 4.1, 3, 50, 
      (SELECT ST_SetSRID(ST_Multi(ST_MakeLine(bus.geom)), 4326)
         FROM model_draft.wn_abw_ego_pf_hv_bus AS bus
         WHERE bus.bus_id in (1851699629, 25600)),
      (SELECT ST_SetSRID(ST_MakeLine(bus.geom), 4326)
         FROM model_draft.wn_abw_ego_pf_hv_bus AS bus
         WHERE bus.bus_id in (1851699629, 25600))
    )
;
```
The second bug #97 is related to eHV..

**Comment by IlkaCu** [comment]
I close this issue as this is not the right place for it. Further discussions take place in open_ego/dataprocessing #207.
