### ISSUE TITLE
missing branches in grid model II

### ISSUE THREAD

**Issue by nesnoj** [openego/eTraGo#97]
(As reported to @IlkaCu via phone)
Some lines at a 380/110kV station (yellow circle) are missing, the 110kV buses (right) are not connected to the station:
![usw](https://user-images.githubusercontent.com/15910173/32952100-763c4eac-cbac-11e7-9e61-486a11f8b71e.png)

Status Quo
v0.2.11
ego_pf_hv_bus.bus_id = 24051

**Comment by IlkaCu** [comment]
![grafik](https://user-images.githubusercontent.com/16799094/32952374-62d6d08e-cbad-11e7-959f-65650290b233.png)
The buses on the right are not inside the substation polygon - so not connected to the substation.

**Comment by ulfmueller** [comment]
Thanks for pointing at that individual bug. Such cases can always occur due to the very flexible osm data logic and heuristics which cannot capture every single exception. We could e.g. widen the buffer around the substation polygons but that would again come along with other problems. The best thing would be probably to check out how the cables are tagged inside of the substation and change the data in osm in order to capture it right with the next osm update.

**Comment by ulfmueller** [comment]
for the debugging, we are talking about ['Umspannwerk Marke'](http://www.openstreetmap.org/way/25526912#map=17/51.74108/12.26223&layers=D)
@ClaraBuettner if you find some time, can you check out the reason for this problem? Or @lukasol do you have a quick idea why this happens?
Some of the lines going into the station do not have a voltage tag which is a fundamental problem and which could be changed. But some have, therefore I do not understand why theses connections are not connected to the substation...

**Comment by ClaraBuettner** [comment]
I just checked the tags in osm, bus I couldn't find the reason. One not-connected line is in the polygon, but I can't see the difference to the others or why it's not connected to the substation.

**Comment by lukasoldi** [comment]
hmm, i don't really know the reason. if i'm not mistaken the default buffer to capture loose ends is roughly 300 m, see: https://github.com/openego/osmTGmod/blob/master/sql-scripts/functions.sql#L1187

but my feeling would also be that this is some kind of an osm issue...

**Comment by nesnoj** [comment]
@ClaraBuettner This bug is related to eHV, do you want to fix it similar to your [recent eHV fixes](https://github.com/openego/data_processing/blob/f832d7c31823c93aab71307c694dca8f1d719e98/utilities/ego_dp_fix_ehv_subnetworks.sql)?

I fixed it manually for my application so I do not depend on your fix but it might be crucial for the eGo grid model @IlkaCu ?

Details:
- I fixed it in derived bus and line tables, not the osmTGmod ones
- my table names hold the prefix "wn_"
- loose ends at 110kV side are connected to 110kV bus of transformer (without altering geoms!)
- unnecessary buses and lines are deleted
```
UPDATE model_draft.wn_abw_ego_pf_hv_line
  SET
    bus1 = 24050
  WHERE line_id = 24022
;
UPDATE model_draft.wn_abw_ego_pf_hv_line
  SET
    bus0 = 24050
  WHERE line_id = 14261
;
UPDATE model_draft.wn_abw_ego_pf_hv_line
  SET
    bus1 = 24050
  WHERE line_id = 19693
;
UPDATE model_draft.wn_abw_ego_pf_hv_line
  SET
    bus0 = 24050
  WHERE line_id = 19472
;
UPDATE model_draft.wn_abw_ego_pf_hv_line
  SET
    bus0 = 24050
  WHERE line_id = 14351
;

-- delete unnecessary lines and buses
DELETE FROM model_draft.wn_abw_ego_pf_hv_line
  WHERE line_id in (20258, 17794)
;
DELETE FROM model_draft.wn_abw_ego_pf_hv_bus
  WHERE bus_id in (17477, 17124, 17939)
;
```

**Comment by ClaraBuettner** [comment]
I'm sorry but I am currently working on my bachelor thesis and just have a few weeks left. So I don't have that much time until the next dp run. I can show you what I did to fix the eHV errors and explain how it worked. It was more or less the same you already wrote, but I didn't referenced to ids, which will change in every dp run. I referenced by the geom and v_nom or s_nom.

**Comment by IlkaCu** [comment]
I close this issue as this is not the right place for it. Further discussions take place in open_ego/dataprocessing #207.

**Comment by nesnoj** [comment]
@ClaraBuettner Sorry for not getting back to you here, I did not adjust dp since I hoped that an OSM update will take place but apparently this is is not going to happen in eGo..

**Comment by IlkaCu** [comment]
We further discussed this issue in ticket [#207 of the DP](https://github.com/openego/data_processing/issues/207#issuecomment-398673703)
